// マスター山カタログ（リスト横断の山の実体）
// 「XX百名山」各リストはこのカタログの山を lists.js で参照する（メンバーシップ方式）。
// 配列の並びは日本百名山の掲載順（北→南）が基準。新規追加分は末尾に積む。
//
// 設計方針:
//   - prefectures / region は必ず schema.js の PREF / REGION を参照する（文字列リテラル禁止）
//   - lat / lng は山頂のおおよその座標（代表値）。厳密な測量値ではない
//   - elevation は標高(m)。出典は国土地理院・環境省等の一般的な山岳標高データに基づく代表値
//   - no（リスト内通し番号）はここには持たない。lists.js の members で持つ
//   - id はリスト横断で安定（登頂記録のキー）。一度割り当てたら変更しない
//   - 同名・別座の山（例: 鳥取の大山 と 丹沢の大山）は name を識別可能名にし alias で補う
//
// 各エントリのスキーマ:
//   {
//     id, name, alias?, reading, elevation,
//     prefectures: [PREF.*], region: REGION.*, lat, lng, source
//   }

const MOUNTAIN = {
  // ── 北海道 ──
  RISHIRIDAKE: { id: "m001", name: "利尻岳", aliases: ["利尻山"], reading: "りしりだけ", elevation: 1721, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 45.178, lng: 141.242, source: "国土地理院" },
  RAUSUDAKE: { id: "m002", name: "羅臼岳", reading: "らうすだけ", elevation: 1661, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 44.077, lng: 145.122, source: "国土地理院" },
  SHYARIDAKE: { id: "m003", name: "斜里岳", reading: "しゃりだけ", elevation: 1547, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.766, lng: 144.721, source: "国土地理院" },
  AKANDAKE: { id: "m004", name: "阿寒岳", aliases: ["雌阿寒岳"], reading: "あかんだけ", elevation: 1499, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.386, lng: 144.009, source: "国土地理院" },
  DAISETSUZAN: { id: "m005", name: "大雪山", aliases: ["旭岳"], reading: "だいせつざん", elevation: 2291, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.663, lng: 142.854, source: "国土地理院" },
  TOMURAUSHIYAMA: { id: "m006", name: "トムラウシ山", reading: "とむらうしやま", elevation: 2141, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.529, lng: 142.851, source: "国土地理院" },
  TOKACHIDAKE: { id: "m007", name: "十勝岳", reading: "とかちだけ", elevation: 2077, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.418, lng: 142.686, source: "国土地理院" },
  POROSHIRIDAKE: { id: "m008", name: "幌尻岳", reading: "ぽろしりだけ", elevation: 2053, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.686, lng: 142.689, source: "国土地理院" },
  YOUTEIZAN: { id: "m009", name: "羊蹄山", aliases: ["後方羊蹄山"], reading: "ようていざん", elevation: 1898, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.827, lng: 140.811, source: "国土地理院" },

  // ── 東北 ──
  IWAKISAN: { id: "m010", name: "岩木山", reading: "いわきさん", elevation: 1625, prefectures: [PREF.AOMORI], region: REGION.TOHOKU, lat: 40.656, lng: 140.303, source: "国土地理院" },
  HAKKOUDASAN: { id: "m011", name: "八甲田山", aliases: ["北八甲田山"], reading: "はっこうださん", elevation: 1585, prefectures: [PREF.AOMORI], region: REGION.TOHOKU, lat: 40.659, lng: 140.877, source: "国土地理院" },
  HACHIMANTAI: { id: "m012", name: "八幡平", reading: "はちまんたい", elevation: 1613, prefectures: [PREF.IWATE, PREF.AKITA], region: REGION.TOHOKU, lat: 39.958, lng: 140.854, source: "国土地理院" },
  IWATESAN: { id: "m013", name: "岩手山", reading: "いわてさん", elevation: 2038, prefectures: [PREF.IWATE], region: REGION.TOHOKU, lat: 39.853, lng: 141.001, source: "国土地理院" },
  HAYACHINESAN: { id: "m014", name: "早池峰山", aliases: ["早池峰"], reading: "はやちねさん", elevation: 1917, prefectures: [PREF.IWATE], region: REGION.TOHOKU, lat: 39.557, lng: 141.489, source: "国土地理院" },
  CHYOUKAISAN: { id: "m015", name: "鳥海山", reading: "ちょうかいさん", elevation: 2236, prefectures: [PREF.YAMAGATA, PREF.AKITA], region: REGION.TOHOKU, lat: 39.099, lng: 140.049, source: "国土地理院" },
  GASSAN: { id: "m016", name: "月山", reading: "がっさん", elevation: 1984, prefectures: [PREF.YAMAGATA], region: REGION.TOHOKU, lat: 38.549, lng: 140.027, source: "国土地理院" },
  ASAHIDAKE: { id: "m017", name: "朝日岳", aliases: ["大朝日岳"], reading: "あさひだけ", elevation: 1871, prefectures: [PREF.YAMAGATA, PREF.NIIGATA], region: REGION.TOHOKU, lat: 38.261, lng: 139.917, source: "国土地理院" },
  ZAOUSAN: { id: "m018", name: "蔵王山", aliases: ["熊野岳"], reading: "ざおうさん", elevation: 1841, prefectures: [PREF.YAMAGATA, PREF.MIYAGI], region: REGION.TOHOKU, lat: 38.144, lng: 140.440, source: "国土地理院" },
  IIDESAN: { id: "m019", name: "飯豊山", reading: "いいでさん", elevation: 2105, prefectures: [PREF.FUKUSHIMA, PREF.YAMAGATA, PREF.NIIGATA], region: REGION.TOHOKU, lat: 37.854, lng: 139.708, source: "国土地理院" },
  AZUMAYAMA: { id: "m020", name: "吾妻山", aliases: ["西吾妻山"], reading: "あづまやま", elevation: 2035, prefectures: [PREF.FUKUSHIMA, PREF.YAMAGATA], region: REGION.TOHOKU, lat: 37.733, lng: 140.246, source: "国土地理院" },
  ADATARAYAMA: { id: "m021", name: "安達太良山", reading: "あだたらやま", elevation: 1700, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.619, lng: 140.288, source: "国土地理院" },
  BANDAISAN: { id: "m022", name: "磐梯山", reading: "ばんだいさん", elevation: 1816, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.601, lng: 140.072, source: "国土地理院" },
  AIZUKOMAGATAKE: { id: "m023", name: "会津駒ヶ岳", reading: "あいづこまがたけ", elevation: 2133, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.046, lng: 139.345, source: "国土地理院" },

  // ── 上信越・尾瀬 / 関東 ──
  NASUDAKE: { id: "m024", name: "那須岳", aliases: ["茶臼岳"], reading: "なすだけ", elevation: 1915, prefectures: [PREF.TOCHIGI], region: REGION.KANTO, lat: 37.122, lng: 139.963, source: "国土地理院" },
  UONUMAKOMAGATAKE: { id: "m025", name: "魚沼駒ヶ岳", aliases: ["越後駒ヶ岳"], reading: "うおぬまこまがたけ", elevation: 2003, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.140, lng: 139.156, source: "国土地理院" },
  HIRAGATAKE: { id: "m026", name: "平ヶ岳", reading: "ひらがたけ", elevation: 2141, prefectures: [PREF.NIIGATA, PREF.GUNMA], region: REGION.JOSHINETSU, lat: 36.943, lng: 139.180, source: "国土地理院" },
  MAKIHATAYAMA: { id: "m027", name: "巻機山", reading: "まきはたやま", elevation: 1967, prefectures: [PREF.NIIGATA, PREF.GUNMA], region: REGION.JOSHINETSU, lat: 36.916, lng: 138.953, source: "国土地理院" },
  HIUCHIGATAKE: { id: "m028", name: "燧ヶ岳", reading: "ひうちがたけ", elevation: 2356, prefectures: [PREF.FUKUSHIMA], region: REGION.JOSHINETSU, lat: 36.955, lng: 139.286, source: "国土地理院" },
  SHIBUTSUSAN: { id: "m029", name: "至仏山", reading: "しぶつさん", elevation: 2228, prefectures: [PREF.GUNMA], region: REGION.JOSHINETSU, lat: 36.903, lng: 139.173, source: "国土地理院" },
  TANIGAWADAKE: { id: "m030", name: "谷川岳", reading: "たにがわだけ", elevation: 1977, prefectures: [PREF.GUNMA, PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 36.834, lng: 138.929, source: "国土地理院" },
  AMAKAZARIYAMA: { id: "m031", name: "雨飾山", reading: "あまかざりやま", elevation: 1963, prefectures: [PREF.NIIGATA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.906, lng: 137.946, source: "国土地理院" },
  NAEBASAN: { id: "m032", name: "苗場山", reading: "なえばさん", elevation: 2145, prefectures: [PREF.NIIGATA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.847, lng: 138.694, source: "国土地理院" },
  MYOUKOUSAN: { id: "m033", name: "妙高山", reading: "みょうこうさん", elevation: 2454, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 36.892, lng: 138.113, source: "国土地理院" },
  HIUCHIYAMA: { id: "m034", name: "火打山", reading: "ひうちやま", elevation: 2462, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 36.921, lng: 138.075, source: "国土地理院" },
  TAKATSUMAYAMA: { id: "m035", name: "高妻山", reading: "たかつまやま", elevation: 2353, prefectures: [PREF.NIIGATA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.808, lng: 138.060, source: "国土地理院" },
  NANTAISAN: { id: "m036", name: "男体山", reading: "なんたいさん", elevation: 2486, prefectures: [PREF.TOCHIGI], region: REGION.KANTO, lat: 36.765, lng: 139.491, source: "国土地理院" },
  NIKKOUSHIRANESAN: { id: "m037", name: "日光白根山", aliases: ["奥白根山"], reading: "にっこうしらねさん", elevation: 2578, prefectures: [PREF.GUNMA, PREF.TOCHIGI], region: REGION.KANTO, lat: 36.798, lng: 139.377, source: "国土地理院" },
  SUKAISAN: { id: "m038", name: "皇海山", reading: "すかいさん", elevation: 2144, prefectures: [PREF.GUNMA, PREF.TOCHIGI], region: REGION.KANTO, lat: 36.701, lng: 139.337, source: "国土地理院" },
  HOTAKAYAMA: { id: "m039", name: "武尊山", aliases: ["上州武尊山"], reading: "ほたかやま", elevation: 2158, prefectures: [PREF.GUNMA], region: REGION.KANTO, lat: 36.802, lng: 139.135, source: "国土地理院" },
  AKAGIYAMA: { id: "m040", name: "赤城山", aliases: ["黒檜山"], reading: "あかぎやま", elevation: 1828, prefectures: [PREF.GUNMA], region: REGION.KANTO, lat: 36.560, lng: 139.193, source: "国土地理院" },
  KUSATSUSHIRANESAN: { id: "m041", name: "草津白根山", reading: "くさつしらねさん", elevation: 2160, prefectures: [PREF.GUNMA], region: REGION.JOSHINETSU, lat: 36.643, lng: 138.528, source: "国土地理院" },
  AZUMAYASAN: { id: "m042", name: "四阿山", reading: "あずまやさん", elevation: 2354, prefectures: [PREF.GUNMA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.534, lng: 138.412, source: "国土地理院" },
  ASAMAYAMA: { id: "m043", name: "浅間山", aliases: ["浅間高原"], reading: "あさまやま", elevation: 2568, prefectures: [PREF.NAGANO, PREF.GUNMA], region: REGION.JOSHINETSU, lat: 36.406, lng: 138.523, source: "国土地理院" },
  TSUKUBASAN: { id: "m044", name: "筑波山", reading: "つくばさん", elevation: 877, prefectures: [PREF.IBARAKI], region: REGION.KANTO, lat: 36.225, lng: 140.107, source: "国土地理院" },

  // ── 北アルプス ──
  SHIROUMADAKE: { id: "m045", name: "白馬岳", reading: "しろうまだけ", elevation: 2932, prefectures: [PREF.NAGANO, PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.758, lng: 137.759, source: "国土地理院" },
  GORYUUDAKE: { id: "m046", name: "五竜岳", reading: "ごりゅうだけ", elevation: 2814, prefectures: [PREF.TOYAMA, PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.658, lng: 137.752, source: "国土地理院" },
  KASHIMAYARIGATAKE: { id: "m047", name: "鹿島槍ヶ岳", reading: "かしまやりがたけ", elevation: 2889, prefectures: [PREF.TOYAMA, PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.624, lng: 137.747, source: "国土地理院" },
  TSURUGIDAKE: { id: "m048", name: "剱岳", aliases: ["早月尾根"], reading: "つるぎだけ", elevation: 2999, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.623, lng: 137.617, source: "国土地理院" },
  TATEYAMA: { id: "m049", name: "立山", aliases: ["大汝山"], reading: "たてやま", elevation: 3015, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.575, lng: 137.618, source: "国土地理院" },
  YAKUSHIDAKE: { id: "m050", name: "薬師岳", reading: "やくしだけ", elevation: 2926, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.466, lng: 137.547, source: "国土地理院" },
  KUROBEGOROUDAKE: { id: "m051", name: "黒部五郎岳", reading: "くろべごろうだけ", elevation: 2840, prefectures: [PREF.TOYAMA, PREF.GIFU], region: REGION.KITA_ALPS, lat: 36.398, lng: 137.539, source: "国土地理院" },
  KURODAKE: { id: "m052", name: "黒岳", aliases: ["水晶岳"], reading: "くろだけ", elevation: 2986, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.408, lng: 137.594, source: "国土地理院" },
  WASHIBADAKE: { id: "m053", name: "鷲羽岳", reading: "わしばだけ", elevation: 2924, prefectures: [PREF.TOYAMA, PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.391, lng: 137.594, source: "国土地理院" },
  YARIGATAKE: { id: "m054", name: "槍ヶ岳", reading: "やりがたけ", elevation: 3180, prefectures: [PREF.NAGANO, PREF.GIFU], region: REGION.KITA_ALPS, lat: 36.342, lng: 137.648, source: "国土地理院" },
  HOTAKADAKE: { id: "m055", name: "穂高岳", aliases: ["奥穂高岳", "西穂高岳"], reading: "ほたかだけ", elevation: 3190, prefectures: [PREF.NAGANO, PREF.GIFU], region: REGION.KITA_ALPS, lat: 36.289, lng: 137.648, source: "国土地理院" },
  JYOUNENDAKE: { id: "m056", name: "常念岳", reading: "じょうねんだけ", elevation: 2857, prefectures: [PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.325, lng: 137.728, source: "国土地理院" },
  KASAGATAKE: { id: "m057", name: "笠ヶ岳", reading: "かさがたけ", elevation: 2898, prefectures: [PREF.GIFU], region: REGION.KITA_ALPS, lat: 36.321, lng: 137.586, source: "国土地理院" },
  YAKEDAKE: { id: "m058", name: "焼岳", reading: "やけだけ", elevation: 2455, prefectures: [PREF.NAGANO, PREF.GIFU], region: REGION.KITA_ALPS, lat: 36.227, lng: 137.587, source: "国土地理院" },
  NORIKURADAKE: { id: "m059", name: "乗鞍岳", aliases: ["剣ヶ峰"], reading: "のりくらだけ", elevation: 3026, prefectures: [PREF.GIFU, PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.106, lng: 137.554, source: "国土地理院" },

  // ── 中部（御嶽・八ヶ岳・奥秩父 ほか） ──
  ONTAKESAN: { id: "m060", name: "御嶽山", aliases: ["剣ヶ峰"], reading: "おんたけさん", elevation: 3067, prefectures: [PREF.NAGANO, PREF.GIFU], region: REGION.CHUBU, lat: 35.893, lng: 137.480, source: "国土地理院" },
  UTSUKUSHIGAHARA: { id: "m061", name: "美ヶ原", aliases: ["王ヶ頭"], reading: "うつくしがはら", elevation: 2034, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.224, lng: 138.103, source: "国土地理院" },
  KIRIGAMINE: { id: "m062", name: "霧ヶ峰", aliases: ["車山"], reading: "きりがみね", elevation: 1925, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.105, lng: 138.193, source: "国土地理院" },
  TATESHINAYAMA: { id: "m063", name: "蓼科山", reading: "たてしなやま", elevation: 2531, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.103, lng: 138.295, source: "国土地理院" },
  YATSUGATAKE: { id: "m064", name: "八ヶ岳", aliases: ["赤岳"], reading: "やつがたけ", elevation: 2899, prefectures: [PREF.NAGANO, PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.971, lng: 138.370, source: "国土地理院" },
  RYOUKAMISAN: { id: "m065", name: "両神山", reading: "りょうかみさん", elevation: 1723, prefectures: [PREF.SAITAMA], region: REGION.KANTO, lat: 35.999, lng: 138.838, source: "国土地理院" },
  KUMOTORIYAMA: { id: "m066", name: "雲取山", reading: "くもとりやま", elevation: 2017, prefectures: [PREF.TOKYO, PREF.SAITAMA, PREF.YAMANASHI], region: REGION.KANTO, lat: 35.857, lng: 138.943, source: "国土地理院" },
  KOBUSHIGATAKE: { id: "m067", name: "甲武信ヶ岳", reading: "こぶしがたけ", elevation: 2475, prefectures: [PREF.SAITAMA, PREF.YAMANASHI, PREF.NAGANO], region: REGION.CHUBU, lat: 35.910, lng: 138.732, source: "国土地理院" },
  KINPUSAN: { id: "m068", name: "金峰山", reading: "きんぷさん", elevation: 2599, prefectures: [PREF.YAMANASHI, PREF.NAGANO], region: REGION.CHUBU, lat: 35.870, lng: 138.625, source: "国土地理院" },
  MIZUGAKIYAMA: { id: "m069", name: "瑞牆山", reading: "みずがきやま", elevation: 2230, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.887, lng: 138.583, source: "国土地理院" },
  DAIBOSATSUDAKE: { id: "m070", name: "大菩薩岳", aliases: ["大菩薩嶺", "大菩薩峠"], reading: "だいぼさつだけ", elevation: 2057, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.748, lng: 138.847, source: "国土地理院" },
  TANZAWASAN: { id: "m071", name: "丹沢山", reading: "たんざわさん", elevation: 1567, prefectures: [PREF.KANAGAWA], region: REGION.KANTO, lat: 35.487, lng: 139.163, source: "国土地理院" },
  FUJISAN: { id: "m072", name: "富士山", reading: "ふじさん", elevation: 3776, prefectures: [PREF.SHIZUOKA, PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.361, lng: 138.728, source: "国土地理院" },
  AMAGISAN: { id: "m073", name: "天城山", aliases: ["万三郎岳"], reading: "あまぎさん", elevation: 1406, prefectures: [PREF.SHIZUOKA], region: REGION.CHUBU, lat: 34.860, lng: 139.005, source: "国土地理院" },

  // ── 中央アルプス ──
  KISOKOMAGATAKE: { id: "m074", name: "木曽駒ヶ岳", reading: "きそこまがたけ", elevation: 2956, prefectures: [PREF.NAGANO], region: REGION.CHUO_ALPS, lat: 35.789, lng: 137.804, source: "国土地理院" },
  UTSUGIDAKE: { id: "m075", name: "空木岳", reading: "うつぎだけ", elevation: 2864, prefectures: [PREF.NAGANO], region: REGION.CHUO_ALPS, lat: 35.726, lng: 137.818, source: "国土地理院" },
  ENASAN: { id: "m076", name: "恵那山", reading: "えなさん", elevation: 2191, prefectures: [PREF.NAGANO, PREF.GIFU], region: REGION.CHUO_ALPS, lat: 35.440, lng: 137.595, source: "国土地理院" },

  // ── 南アルプス ──
  KAIKOMAGATAKE: { id: "m077", name: "甲斐駒ヶ岳", reading: "かいこまがたけ", elevation: 2967, prefectures: [PREF.YAMANASHI, PREF.NAGANO], region: REGION.MINAMI_ALPS, lat: 35.758, lng: 138.237, source: "国土地理院" },
  SENJYOUGATAKE: { id: "m078", name: "仙丈ヶ岳", reading: "せんじょうがたけ", elevation: 3033, prefectures: [PREF.YAMANASHI, PREF.NAGANO], region: REGION.MINAMI_ALPS, lat: 35.720, lng: 138.183, source: "国土地理院" },
  HOUOUZAN: { id: "m079", name: "鳳凰山", aliases: ["観音岳", "鳳凰三山"], reading: "ほうおうざん", elevation: 2840, prefectures: [PREF.YAMANASHI], region: REGION.MINAMI_ALPS, lat: 35.696, lng: 138.297, source: "国土地理院" },
  KITADAKE: { id: "m080", name: "北岳", reading: "きただけ", elevation: 3193, prefectures: [PREF.YAMANASHI], region: REGION.MINAMI_ALPS, lat: 35.674, lng: 138.239, source: "国土地理院" },
  AINODAKE: { id: "m081", name: "間ノ岳", reading: "あいのだけ", elevation: 3190, prefectures: [PREF.YAMANASHI, PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.646, lng: 138.228, source: "国土地理院" },
  SHIOMIDAKE: { id: "m082", name: "塩見岳", reading: "しおみだけ", elevation: 3052, prefectures: [PREF.NAGANO, PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.567, lng: 138.177, source: "国土地理院" },
  WARUSAWADAKE: { id: "m083", name: "悪沢岳", aliases: ["荒川東岳"], reading: "わるさわだけ", elevation: 3141, prefectures: [PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.487, lng: 138.181, source: "国土地理院" },
  AKAISHIDAKE: { id: "m084", name: "赤石岳", reading: "あかいしだけ", elevation: 3121, prefectures: [PREF.NAGANO, PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.461, lng: 138.158, source: "国土地理院" },
  HIJIRIDAKE: { id: "m085", name: "聖岳", reading: "ひじりだけ", elevation: 3013, prefectures: [PREF.NAGANO, PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.424, lng: 138.143, source: "国土地理院" },
  TEKARIDAKE: { id: "m086", name: "光岳", reading: "てかりだけ", elevation: 2592, prefectures: [PREF.NAGANO, PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.336, lng: 138.092, source: "国土地理院" },

  // ── 北陸・近畿 ──
  HAKUSAN: { id: "m087", name: "白山", aliases: ["御前峰"], reading: "はくさん", elevation: 2702, prefectures: [PREF.ISHIKAWA, PREF.GIFU], region: REGION.CHUBU, lat: 36.155, lng: 136.771, source: "国土地理院" },
  ARASHIMADAKE: { id: "m088", name: "荒島岳", reading: "あらしまだけ", elevation: 1523, prefectures: [PREF.FUKUI], region: REGION.CHUBU, lat: 35.928, lng: 136.598, source: "国土地理院" },
  IBUKIYAMA: { id: "m089", name: "伊吹山", reading: "いぶきやま", elevation: 1377, prefectures: [PREF.SHIGA, PREF.GIFU], region: REGION.KINKI, lat: 35.418, lng: 136.406, source: "国土地理院" },
  OODAIGAHARAYAMA: { id: "m090", name: "大台ヶ原山", aliases: ["日出ヶ岳", "大杉谷"], reading: "おおだいがはらやま", elevation: 1695, prefectures: [PREF.NARA, PREF.MIE], region: REGION.KINKI, lat: 34.182, lng: 136.105, source: "国土地理院" },
  OOMINESAN: { id: "m091", name: "大峰山", aliases: ["八経ヶ岳"], reading: "おおみねさん", elevation: 1915, prefectures: [PREF.NARA], region: REGION.KINKI, lat: 34.173, lng: 135.910, source: "国土地理院" },

  // ── 中国・四国 ──
  DAISEN: { id: "m092", name: "大山", aliases: ["剣ヶ峰"], reading: "だいせん", elevation: 1729, prefectures: [PREF.TOTTORI], region: REGION.CHUGOKU, lat: 35.371, lng: 133.546, source: "国土地理院" },
  TSURUGISAN: { id: "m093", name: "剣山", reading: "つるぎさん", elevation: 1955, prefectures: [PREF.TOKUSHIMA], region: REGION.CHUGOKU, lat: 33.854, lng: 134.094, source: "国土地理院" },
  ISHIZUCHISAN: { id: "m094", name: "石鎚山", aliases: ["天狗岳"], reading: "いしづちさん", elevation: 1982, prefectures: [PREF.EHIME], region: REGION.CHUGOKU, lat: 33.768, lng: 133.115, source: "国土地理院" },

  // ── 九州 ──
  KUJYUUSAN: { id: "m095", name: "九重山", aliases: ["中岳", "久住山"], reading: "くじゅうさん", elevation: 1791, prefectures: [PREF.OITA], region: REGION.KYUSHU, lat: 33.086, lng: 131.249, source: "国土地理院" },
  SOBOSAN: { id: "m096", name: "祖母山", reading: "そぼさん", elevation: 1756, prefectures: [PREF.OITA, PREF.MIYAZAKI], region: REGION.KYUSHU, lat: 32.825, lng: 131.347, source: "国土地理院" },
  ASOSAN: { id: "m097", name: "阿蘇山", aliases: ["高岳", "阿蘇高原"], reading: "あそさん", elevation: 1592, prefectures: [PREF.KUMAMOTO], region: REGION.KYUSHU, lat: 32.884, lng: 131.104, source: "国土地理院" },
  KIRISHIMAYAMA: { id: "m098", name: "霧島山", aliases: ["韓国岳", "霧島連峰"], reading: "きりしまやま", elevation: 1700, prefectures: [PREF.KAGOSHIMA, PREF.MIYAZAKI], region: REGION.KYUSHU, lat: 31.934, lng: 130.862, source: "国土地理院" },
  KAIMONDAKE: { id: "m099", name: "開聞岳", reading: "かいもんだけ", elevation: 924, prefectures: [PREF.KAGOSHIMA], region: REGION.KYUSHU, lat: 31.180, lng: 130.528, source: "国土地理院" },
  MIYANOURADAKE: { id: "m100", name: "宮之浦岳", reading: "みやのうらだけ", elevation: 1936, prefectures: [PREF.KAGOSHIMA], region: REGION.KYUSHU, lat: 30.337, lng: 130.508, source: "国土地理院" },

  // ── 日本二百名山 追加分（深田クラブ選定の +100座 / m101..m200） ──
  // 標高は国土地理院ベースの代表値。lat/lng は代表値（要精査）。
  TESHIODAKE: { id: "m101", name: "天塩岳", reading: "てしおだけ", elevation: 1558, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.967, lng: 142.917, source: "国土地理院" },
  ISHIKARIDAKE: { id: "m102", name: "石狩岳", reading: "いしかりだけ", elevation: 1967, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.483, lng: 143.033, source: "国土地理院" },
  NIPESOTSUYAMA: { id: "m103", name: "ニペソツ山", reading: "にぺそつやま", elevation: 2013, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.383, lng: 143.017, source: "国土地理院" },
  KAMUIEKUUCHIKAUSHIYAMA: { id: "m104", name: "カムイエクウチカウシ山", reading: "かむいえくうちかうしやま", elevation: 1979, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.583, lng: 142.950, source: "国土地理院" },
  PETEGARIDAKE: { id: "m105", name: "ペテガリ岳", reading: "ぺてがりだけ", elevation: 1736, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.467, lng: 142.950, source: "国土地理院" },
  ASHIBETSUDAKE: { id: "m106", name: "芦別岳", reading: "あしべつだけ", elevation: 1726, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.283, lng: 142.467, source: "国土地理院" },
  YUUBARIDAKE: { id: "m107", name: "夕張岳", reading: "ゆうばりだけ", elevation: 1668, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.100, lng: 142.317, source: "国土地理院" },
  SHYOKANBETSUDAKE: { id: "m108", name: "暑寒別岳", reading: "しょかんべつだけ", elevation: 1492, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.717, lng: 141.567, source: "国土地理院" },
  TARUMAEYAMA: { id: "m109", name: "樽前山", reading: "たるまえやま", elevation: 1041, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.683, lng: 141.383, source: "国土地理院" },
  HOKKAIDOUKOMAGATAKE: { id: "m110", name: "北海道駒ヶ岳", reading: "ほっかいどうこまがたけ", elevation: 1131, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.067, lng: 140.683, source: "国土地理院" },
  SHIRAKAMIDAKE: { id: "m111", name: "白神岳", reading: "しらかみだけ", elevation: 1235, prefectures: [PREF.AOMORI], region: REGION.TOHOKU, lat: 40.483, lng: 139.967, source: "国土地理院" },
  HIMEKAMIYAMA: { id: "m112", name: "姫神山", reading: "ひめかみやま", elevation: 1124, prefectures: [PREF.IWATE], region: REGION.TOHOKU, lat: 39.850, lng: 141.233, source: "国土地理院" },
  AKITAKOMAGATAKE: { id: "m113", name: "秋田駒ヶ岳", reading: "あきたこまがたけ", elevation: 1637, prefectures: [PREF.AKITA], region: REGION.TOHOKU, lat: 39.750, lng: 140.800, source: "国土地理院" },
  WAGADAKE: { id: "m114", name: "和賀岳", reading: "わがだけ", elevation: 1439, prefectures: [PREF.IWATE, PREF.AKITA], region: REGION.TOHOKU, lat: 39.400, lng: 140.733, source: "国土地理院" },
  MORIYOSHIZAN: { id: "m115", name: "森吉山", reading: "もりよしざん", elevation: 1454, prefectures: [PREF.AKITA], region: REGION.TOHOKU, lat: 39.983, lng: 140.550, source: "国土地理院" },
  YAKEISHIDAKE: { id: "m116", name: "焼石岳", reading: "やけいしだけ", elevation: 1547, prefectures: [PREF.IWATE], region: REGION.TOHOKU, lat: 39.167, lng: 140.833, source: "国土地理院" },
  KURIKOMAYAMA: { id: "m117", name: "栗駒山", reading: "くりこまやま", elevation: 1626, prefectures: [PREF.IWATE, PREF.MIYAGI, PREF.AKITA], region: REGION.TOHOKU, lat: 38.950, lng: 140.783, source: "国土地理院" },
  KAMUROYAMA: { id: "m118", name: "神室山", reading: "かむろやま", elevation: 1365, prefectures: [PREF.YAMAGATA, PREF.AKITA], region: REGION.TOHOKU, lat: 38.917, lng: 140.483, source: "国土地理院" },
  FUNAGATAYAMA: { id: "m119", name: "船形山", reading: "ふながたやま", elevation: 1500, prefectures: [PREF.MIYAGI, PREF.YAMAGATA], region: REGION.TOHOKU, lat: 38.450, lng: 140.617, source: "国土地理院" },
  ITOUDAKE: { id: "m120", name: "以東岳", reading: "いとうだけ", elevation: 1772, prefectures: [PREF.YAMAGATA, PREF.NIIGATA], region: REGION.TOHOKU, lat: 38.317, lng: 139.717, source: "国土地理院" },
  EBURISASHIDAKE: { id: "m121", name: "朳差岳", reading: "えぶりさしだけ", elevation: 1636, prefectures: [PREF.NIIGATA], region: REGION.TOHOKU, lat: 37.950, lng: 139.617, source: "国土地理院" },
  NINOUJIDAKE: { id: "m122", name: "二王子岳", reading: "にのうじだけ", elevation: 1420, prefectures: [PREF.NIIGATA], region: REGION.TOHOKU, lat: 37.850, lng: 139.483, source: "国土地理院" },
  TAISHYAKUSAN: { id: "m123", name: "帝釈山", reading: "たいしゃくさん", elevation: 2060, prefectures: [PREF.FUKUSHIMA, PREF.TOCHIGI], region: REGION.TOHOKU, lat: 36.950, lng: 139.500, source: "国土地理院" },
  AIZUASAHIDAKE: { id: "m124", name: "会津朝日岳", reading: "あいづあさひだけ", elevation: 1624, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.117, lng: 139.367, source: "国土地理院" },
  NYOHOUSAN: { id: "m125", name: "女峰山", reading: "にょほうさん", elevation: 2483, prefectures: [PREF.TOCHIGI], region: REGION.KANTO, lat: 36.783, lng: 139.517, source: "国土地理院" },
  SENNOKURAYAMA: { id: "m126", name: "仙ノ倉山", reading: "せんのくらやま", elevation: 2026, prefectures: [PREF.NIIGATA, PREF.GUNMA], region: REGION.JOSHINETSU, lat: 36.800, lng: 138.817, source: "国土地理院" },
  HARUNASAN: { id: "m127", name: "榛名山", reading: "はるなさん", elevation: 1449, prefectures: [PREF.GUNMA], region: REGION.KANTO, lat: 36.483, lng: 138.867, source: "国土地理院" },
  ASAMAKAKUSHIYAMA: { id: "m128", name: "浅間隠山", reading: "あさまかくしやま", elevation: 1757, prefectures: [PREF.GUNMA], region: REGION.KANTO, lat: 36.483, lng: 138.650, source: "国土地理院" },
  MYOUGISAN: { id: "m129", name: "妙義山", reading: "みょうぎさん", elevation: 1104, prefectures: [PREF.GUNMA], region: REGION.KANTO, lat: 36.300, lng: 138.733, source: "国土地理院" },
  ARAFUNEYAMA: { id: "m130", name: "荒船山", reading: "あらふねやま", elevation: 1423, prefectures: [PREF.GUNMA, PREF.NAGANO], region: REGION.KANTO, lat: 36.217, lng: 138.667, source: "国土地理院" },
  BUKOUSAN: { id: "m131", name: "武甲山", reading: "ぶこうさん", elevation: 1304, prefectures: [PREF.SAITAMA], region: REGION.KANTO, lat: 35.950, lng: 139.100, source: "国土地理院" },
  WANAKURAYAMA: { id: "m132", name: "和名倉山", aliases: ["白石山"], reading: "わなくらやま", elevation: 2036, prefectures: [PREF.SAITAMA], region: REGION.KANTO, lat: 35.900, lng: 138.850, source: "国土地理院" },
  OODAKESAN: { id: "m133", name: "大岳山", reading: "おおだけさん", elevation: 1266, prefectures: [PREF.TOKYO], region: REGION.KANTO, lat: 35.800, lng: 139.133, source: "国土地理院" },
  MIKAGURADAKE: { id: "m134", name: "御神楽岳", reading: "みかぐらだけ", elevation: 1386, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.550, lng: 139.400, source: "国土地理院" },
  SUMONDAKE: { id: "m135", name: "守門岳", reading: "すもんだけ", elevation: 1537, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.317, lng: 139.183, source: "国土地理院" },
  HAKKAISAN: { id: "m136", name: "八海山", reading: "はっかいさん", elevation: 1778, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.150, lng: 138.967, source: "国土地理院" },
  ARASAWADAKE: { id: "m137", name: "荒沢岳", reading: "あらさわだけ", elevation: 1969, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.050, lng: 139.200, source: "国土地理院" },
  NAKANODAKE: { id: "m138", name: "中ノ岳", reading: "なかのだけ", elevation: 2085, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.100, lng: 139.050, source: "国土地理院" },
  SABURYUUYAMA: { id: "m139", name: "佐武流山", reading: "さぶりゅうやま", elevation: 2192, prefectures: [PREF.NIIGATA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.850, lng: 138.617, source: "国土地理院" },
  SHIRASUNAYAMA: { id: "m140", name: "白砂山", reading: "しらすなやま", elevation: 2140, prefectures: [PREF.GUNMA, PREF.NIIGATA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.717, lng: 138.617, source: "国土地理院" },
  TORIKABUTOYAMA: { id: "m141", name: "鳥甲山", reading: "とりかぶとやま", elevation: 2038, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.850, lng: 138.567, source: "国土地理院" },
  IWASUGEYAMA: { id: "m142", name: "岩菅山", reading: "いわすげやま", elevation: 2295, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.733, lng: 138.550, source: "国土地理院" },
  IIZUNAYAMA: { id: "m143", name: "飯縄山", reading: "いいづなやま", elevation: 1917, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.733, lng: 138.117, source: "国土地理院" },
  KUROHIMEYAMA: { id: "m144", name: "黒姫山", reading: "くろひめやま", elevation: 2053, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.817, lng: 138.133, source: "国土地理院" },
  TOGAKUSHIYAMA: { id: "m145", name: "戸隠山", reading: "とがくしやま", elevation: 1904, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.783, lng: 138.067, source: "国土地理院" },
  TENGUDAKE: { id: "m146", name: "天狗岳", reading: "てんぐだけ", elevation: 2646, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.050, lng: 138.367, source: "国土地理院" },
  OGURASAN: { id: "m147", name: "御座山", reading: "おぐらさん", elevation: 2112, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.050, lng: 138.567, source: "国土地理院" },
  KENTOKUSAN: { id: "m148", name: "乾徳山", reading: "けんとくさん", elevation: 2031, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.783, lng: 138.717, source: "国土地理院" },
  KAYAGATAKE: { id: "m149", name: "茅ヶ岳", reading: "かやがたけ", elevation: 1704, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.750, lng: 138.500, source: "国土地理院" },
  MISHYOUTAISAN: { id: "m150", name: "御正体山", reading: "みしょうたいさん", elevation: 1681, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.450, lng: 138.917, source: "国土地理院" },
  MITSUTOUGEYAMA: { id: "m151", name: "三ツ峠山", reading: "みつとうげやま", elevation: 1785, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.567, lng: 138.800, source: "国土地理院" },
  KENASHIYAMA: { id: "m152", name: "毛無山", reading: "けなしやま", elevation: 1964, prefectures: [PREF.YAMANASHI, PREF.SHIZUOKA], region: REGION.CHUBU, lat: 35.467, lng: 138.583, source: "国土地理院" },
  KUSHIGATAYAMA: { id: "m153", name: "櫛形山", reading: "くしがたやま", elevation: 2052, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.567, lng: 138.367, source: "国土地理院" },
  SHICHIMENZAN: { id: "m154", name: "七面山", reading: "しちめんざん", elevation: 1989, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.367, lng: 138.350, source: "国土地理院" },
  YUKIKURADAKE: { id: "m155", name: "雪倉岳", reading: "ゆきくらだけ", elevation: 2611, prefectures: [PREF.TOYAMA, PREF.NIIGATA], region: REGION.KITA_ALPS, lat: 36.817, lng: 137.783, source: "国土地理院" },
  HARINOKIDAKE: { id: "m156", name: "針ノ木岳", reading: "はりのきだけ", elevation: 2821, prefectures: [PREF.TOYAMA, PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.567, lng: 137.650, source: "国土地理院" },
  KEKACHIYAMA: { id: "m157", name: "毛勝山", reading: "けかちやま", elevation: 2415, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.683, lng: 137.617, source: "国土地理院" },
  OKUDAINICHIDAKE: { id: "m158", name: "奥大日岳", aliases: ["大日連峰"], reading: "おくだいにちだけ", elevation: 2611, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.600, lng: 137.583, source: "国土地理院" },
  EBOSHIDAKE: { id: "m159", name: "烏帽子岳", reading: "えぼしだけ", elevation: 2628, prefectures: [PREF.TOYAMA, PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.450, lng: 137.617, source: "国土地理院" },
  AKAUSHIDAKE: { id: "m160", name: "赤牛岳", reading: "あかうしだけ", elevation: 2864, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.433, lng: 137.617, source: "国土地理院" },
  GAKIDAKE: { id: "m161", name: "餓鬼岳", reading: "がきだけ", elevation: 2647, prefectures: [PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.450, lng: 137.733, source: "国土地理院" },
  ARIAKEYAMA: { id: "m162", name: "有明山", reading: "ありあけやま", elevation: 2268, prefectures: [PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.400, lng: 137.750, source: "国土地理院" },
  TSUBAKURODAKE: { id: "m163", name: "燕岳", reading: "つばくろだけ", elevation: 2763, prefectures: [PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.400, lng: 137.717, source: "国土地理院" },
  OTENSHYOUDAKE: { id: "m164", name: "大天井岳", reading: "おてんしょうだけ", elevation: 2922, prefectures: [PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.350, lng: 137.717, source: "国土地理院" },
  KASUMISAWADAKE: { id: "m165", name: "霞沢岳", reading: "かすみさわだけ", elevation: 2646, prefectures: [PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.233, lng: 137.633, source: "国土地理院" },
  KYOUGATAKE: { id: "m166", name: "経ヶ岳", reading: "きょうがたけ", elevation: 2296, prefectures: [PREF.NAGANO], region: REGION.CHUO_ALPS, lat: 35.917, lng: 137.850, source: "国土地理院" },
  MINAMIKOMAGATAKE: { id: "m167", name: "南駒ヶ岳", reading: "みなみこまがたけ", elevation: 2841, prefectures: [PREF.NAGANO], region: REGION.CHUO_ALPS, lat: 35.683, lng: 137.817, source: "国土地理院" },
  ANPEIJIYAMA: { id: "m168", name: "安平路山", reading: "あんぺいじやま", elevation: 2363, prefectures: [PREF.NAGANO], region: REGION.CHUO_ALPS, lat: 35.583, lng: 137.783, source: "国土地理院" },
  KOHIDEYAMA: { id: "m169", name: "小秀山", reading: "こひでやま", elevation: 1982, prefectures: [PREF.NAGANO, PREF.GIFU], region: REGION.CHUBU, lat: 35.783, lng: 137.517, source: "国土地理院" },
  NOKOGIRIDAKE: { id: "m170", name: "鋸岳", reading: "のこぎりだけ", elevation: 2685, prefectures: [PREF.YAMANASHI, PREF.NAGANO], region: REGION.MINAMI_ALPS, lat: 35.783, lng: 138.200, source: "国土地理院" },
  NOUTORIDAKE: { id: "m171", name: "農鳥岳", reading: "のうとりだけ", elevation: 3026, prefectures: [PREF.YAMANASHI, PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.617, lng: 138.233, source: "国土地理院" },
  ZARUGATAKE: { id: "m172", name: "笊ヶ岳", reading: "ざるがたけ", elevation: 2629, prefectures: [PREF.YAMANASHI, PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.517, lng: 138.250, source: "国土地理院" },
  KAMIKOUCHIDAKE: { id: "m173", name: "上河内岳", reading: "かみこうちだけ", elevation: 2803, prefectures: [PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.400, lng: 138.167, source: "国土地理院" },
  IKEGUCHIDAKE: { id: "m174", name: "池口岳", reading: "いけぐちだけ", elevation: 2392, prefectures: [PREF.NAGANO, PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.300, lng: 138.050, source: "国土地理院" },
  DAIMUGENZAN: { id: "m175", name: "大無間山", reading: "だいむげんざん", elevation: 2330, prefectures: [PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.300, lng: 138.167, source: "国土地理院" },
  ASHITAKAYAMA: { id: "m176", name: "愛鷹山", reading: "あしたかやま", elevation: 1504, prefectures: [PREF.SHIZUOKA], region: REGION.CHUBU, lat: 35.217, lng: 138.817, source: "国土地理院" },
  KONGOUDOUZAN: { id: "m177", name: "金剛堂山", reading: "こんごうどうざん", elevation: 1650, prefectures: [PREF.TOYAMA], region: REGION.CHUBU, lat: 36.400, lng: 137.050, source: "国土地理院" },
  KURAIYAMA: { id: "m178", name: "位山", reading: "くらいやま", elevation: 1529, prefectures: [PREF.GIFU], region: REGION.CHUBU, lat: 36.100, lng: 137.250, source: "国土地理院" },
  OIZURUGATAKE: { id: "m179", name: "笈ヶ岳", reading: "おいずるがたけ", elevation: 1841, prefectures: [PREF.ISHIKAWA, PREF.GIFU, PREF.TOYAMA], region: REGION.CHUBU, lat: 36.300, lng: 136.783, source: "国土地理院" },
  DAINICHIGATAKE: { id: "m180", name: "大日ヶ岳", reading: "だいにちがたけ", elevation: 1709, prefectures: [PREF.GIFU], region: REGION.CHUBU, lat: 35.950, lng: 136.850, source: "国土地理院" },
  NOUGOUHAKUSAN: { id: "m181", name: "能郷白山", reading: "のうごうはくさん", elevation: 1617, prefectures: [PREF.GIFU, PREF.FUKUI], region: REGION.CHUBU, lat: 35.717, lng: 136.500, source: "国土地理院" },
  GOZAISHYODAKE: { id: "m182", name: "御在所岳", reading: "ございしょだけ", elevation: 1212, prefectures: [PREF.MIE, PREF.SHIGA], region: REGION.KINKI, lat: 35.017, lng: 136.417, source: "国土地理院" },
  SHYAKAGATAKE: { id: "m183", name: "釈迦ヶ岳", reading: "しゃかがたけ", elevation: 1800, prefectures: [PREF.NARA], region: REGION.KINKI, lat: 34.100, lng: 135.900, source: "国土地理院" },
  OBAKODAKE: { id: "m184", name: "伯母子岳", reading: "おばこだけ", elevation: 1344, prefectures: [PREF.NARA, PREF.WAKAYAMA], region: REGION.KINKI, lat: 34.083, lng: 135.617, source: "国土地理院" },
  KONGOUSAN: { id: "m185", name: "金剛山", reading: "こんごうさん", elevation: 1125, prefectures: [PREF.OSAKA, PREF.NARA], region: REGION.KINKI, lat: 34.417, lng: 135.683, source: "国土地理院" },
  BUNAGATAKE: { id: "m186", name: "武奈ヶ岳", reading: "ぶながたけ", elevation: 1214, prefectures: [PREF.SHIGA], region: REGION.KINKI, lat: 35.233, lng: 135.883, source: "国土地理院" },
  HYOUNOSEN: { id: "m187", name: "氷ノ山", reading: "ひょうのせん", elevation: 1510, prefectures: [PREF.HYOGO, PREF.TOTTORI], region: REGION.CHUGOKU, lat: 35.350, lng: 134.517, source: "国土地理院" },
  KAMIHIRUZEN: { id: "m188", name: "上蒜山", aliases: ["蒜山"], reading: "かみひるぜん", elevation: 1202, prefectures: [PREF.OKAYAMA, PREF.TOTTORI], region: REGION.CHUGOKU, lat: 35.367, lng: 133.650, source: "国土地理院" },
  SANBESAN: { id: "m189", name: "三瓶山", reading: "さんべさん", elevation: 1126, prefectures: [PREF.SHIMANE], region: REGION.CHUGOKU, lat: 35.133, lng: 132.617, source: "国土地理院" },
  MIUNE: { id: "m190", name: "三嶺", reading: "みうね", elevation: 1894, prefectures: [PREF.TOKUSHIMA, PREF.KOCHI], region: REGION.CHUGOKU, lat: 33.817, lng: 133.967, source: "国土地理院" },
  HIGASHIAKAISHIYAMA: { id: "m191", name: "東赤石山", reading: "ひがしあかいしやま", elevation: 1706, prefectures: [PREF.EHIME], region: REGION.CHUGOKU, lat: 33.850, lng: 133.350, source: "国土地理院" },
  SASAGAMINE: { id: "m192", name: "笹ヶ峰", reading: "ささがみね", elevation: 1860, prefectures: [PREF.EHIME, PREF.KOCHI], region: REGION.CHUGOKU, lat: 33.850, lng: 133.300, source: "国土地理院" },
  HIKOSAN: { id: "m193", name: "英彦山", reading: "ひこさん", elevation: 1199, prefectures: [PREF.FUKUOKA, PREF.OITA], region: REGION.KYUSHU, lat: 33.483, lng: 130.900, source: "国土地理院" },
  YUFUDAKE: { id: "m194", name: "由布岳", reading: "ゆふだけ", elevation: 1583, prefectures: [PREF.OITA], region: REGION.KYUSHU, lat: 33.283, lng: 131.400, source: "国土地理院" },
  OOKUEYAMA: { id: "m195", name: "大崩山", reading: "おおくえやま", elevation: 1644, prefectures: [PREF.MIYAZAKI], region: REGION.KYUSHU, lat: 32.717, lng: 131.450, source: "国土地理院" },
  UNZENDAKE: { id: "m196", name: "雲仙岳", reading: "うんぜんだけ", elevation: 1483, prefectures: [PREF.NAGASAKI], region: REGION.KYUSHU, lat: 32.767, lng: 130.300, source: "国土地理院" },
  ICHIFUSAYAMA: { id: "m197", name: "市房山", reading: "いちふさやま", elevation: 1721, prefectures: [PREF.KUMAMOTO, PREF.MIYAZAKI], region: REGION.KYUSHU, lat: 32.317, lng: 131.050, source: "国土地理院" },
  OSUZUYAMA: { id: "m198", name: "尾鈴山", reading: "おすずやま", elevation: 1405, prefectures: [PREF.MIYAZAKI], region: REGION.KYUSHU, lat: 32.317, lng: 131.300, source: "国土地理院" },
  TAKACHIHONOMINE: { id: "m199", name: "高千穂峰", reading: "たかちほのみね", elevation: 1574, prefectures: [PREF.MIYAZAKI, PREF.KAGOSHIMA], region: REGION.KYUSHU, lat: 31.886, lng: 130.919, source: "国土地理院" },
  SAKURAJIMA: { id: "m200", name: "桜島", reading: "さくらじま", elevation: 1117, prefectures: [PREF.KAGOSHIMA], region: REGION.KYUSHU, lat: 31.583, lng: 130.650, source: "国土地理院" },

  // ── 日本三百名山 追加分（日本山岳会系の +101座 / m201..m301） ──
  // 標高は国土地理院ベースの代表値。lat/lng は代表値（要精査）。
  NISEIKAUSHYUPPEYAMA: { id: "m201", name: "ニセイカウシュッペ山", reading: "にせいかうしゅっぺやま", elevation: 1883, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.850, lng: 142.950, source: "国土地理院" },
  OPUTATESHIKEYAMA: { id: "m202", name: "オプタテシケ山", reading: "おぷたてしけやま", elevation: 2013, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.450, lng: 142.800, source: "国土地理院" },
  KAMUIDAKE: { id: "m203", name: "神威岳", reading: "かむいだけ", elevation: 1600, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.450, lng: 142.880, source: "国土地理院" },
  YOICHIDAKE: { id: "m204", name: "余市岳", reading: "よいちだけ", elevation: 1488, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.900, lng: 141.100, source: "国土地理院" },
  NISEKOANNUPURI: { id: "m205", name: "ニセコアンヌプリ", reading: "にせこあんぬぷり", elevation: 1308, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.860, lng: 140.630, source: "国土地理院" },
  KARIBAYAMA: { id: "m206", name: "狩場山", reading: "かりばやま", elevation: 1520, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.550, lng: 140.100, source: "国土地理院" },
  OOSENGENDAKE: { id: "m207", name: "大千軒岳", reading: "おおせんげんだけ", elevation: 1072, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 41.550, lng: 140.100, source: "国土地理院" },
  GOYOUZAN: { id: "m208", name: "五葉山", reading: "ごようざん", elevation: 1351, prefectures: [PREF.IWATE], region: REGION.TOHOKU, lat: 39.200, lng: 141.700, source: "国土地理院" },
  NYUUTOUZAN: { id: "m209", name: "乳頭山", reading: "にゅうとうざん", elevation: 1478, prefectures: [PREF.AKITA, PREF.IWATE], region: REGION.TOHOKU, lat: 39.800, lng: 140.820, source: "国土地理院" },
  TAIHEIZAN: { id: "m210", name: "太平山", reading: "たいへいざん", elevation: 1170, prefectures: [PREF.AKITA], region: REGION.TOHOKU, lat: 39.800, lng: 140.400, source: "国土地理院" },
  IZUMIGATAKE: { id: "m211", name: "泉ヶ岳", reading: "いずみがたけ", elevation: 1175, prefectures: [PREF.MIYAGI], region: REGION.TOHOKU, lat: 38.400, lng: 140.700, source: "国土地理院" },
  MAYASAN: { id: "m212", name: "摩耶山", reading: "まやさん", elevation: 1020, prefectures: [PREF.YAMAGATA], region: REGION.TOHOKU, lat: 38.650, lng: 139.700, source: "国土地理院" },
  IWAIGAMEYAMA: { id: "m213", name: "祝瓶山", reading: "いわいがめやま", elevation: 1417, prefectures: [PREF.YAMAGATA], region: REGION.TOHOKU, lat: 38.150, lng: 139.850, source: "国土地理院" },
  ISSAIKYOUZAN: { id: "m214", name: "一切経山", reading: "いっさいきょうざん", elevation: 1949, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.730, lng: 140.280, source: "国土地理院" },
  OOTAKINEYAMA: { id: "m215", name: "大滝根山", reading: "おおたきねやま", elevation: 1192, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.400, lng: 140.700, source: "国土地理院" },
  FUTAMATAYAMA: { id: "m216", name: "二岐山", reading: "ふたまたやま", elevation: 1544, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.250, lng: 140.000, source: "国土地理院" },
  NANATSUGATAKE: { id: "m217", name: "七ヶ岳", reading: "ななつがたけ", elevation: 1636, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.100, lng: 139.700, source: "国土地理院" },
  ARAKAIYAMA: { id: "m218", name: "荒海山", reading: "あらかいやま", elevation: 1581, prefectures: [PREF.FUKUSHIMA, PREF.TOCHIGI], region: REGION.TOHOKU, lat: 37.000, lng: 139.650, source: "国土地理院" },
  YAMIZOSAN: { id: "m219", name: "八溝山", reading: "やみぞさん", elevation: 1022, prefectures: [PREF.IBARAKI, PREF.FUKUSHIMA], region: REGION.KANTO, lat: 36.970, lng: 140.320, source: "国土地理院" },
  OJIKADAKE: { id: "m220", name: "男鹿岳", reading: "おじかだけ", elevation: 1777, prefectures: [PREF.TOCHIGI, PREF.FUKUSHIMA], region: REGION.KANTO, lat: 36.980, lng: 139.730, source: "国土地理院" },
  TAKAHARAYAMA: { id: "m221", name: "高原山", aliases: ["鶏頂山"], reading: "たかはらやま", elevation: 1795, prefectures: [PREF.TOCHIGI], region: REGION.KANTO, lat: 36.900, lng: 139.780, source: "国土地理院" },
  TAROUSAN: { id: "m222", name: "太郎山", reading: "たろうさん", elevation: 2368, prefectures: [PREF.TOCHIGI], region: REGION.KANTO, lat: 36.800, lng: 139.450, source: "国土地理院" },
  KESAMARUYAMA: { id: "m223", name: "袈裟丸山", reading: "けさまるやま", elevation: 1961, prefectures: [PREF.GUNMA, PREF.TOCHIGI], region: REGION.KANTO, lat: 36.620, lng: 139.300, source: "国土地理院" },
  KEIZURUYAMA: { id: "m224", name: "景鶴山", reading: "けいづるやま", elevation: 2004, prefectures: [PREF.GUNMA, PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 36.950, lng: 139.250, source: "国土地理院" },
  ASAHIDAKE_TOCHIGI: { id: "m225", name: "朝日岳（那須）", aliases: ["朝日岳"], reading: "あさひだけ", elevation: 1945, prefectures: [PREF.TOCHIGI], region: REGION.KANTO, lat: 37.080, lng: 139.950, source: "国土地理院" },
  SUWAYAMA: { id: "m226", name: "諏訪山", reading: "すわやま", elevation: 1549, prefectures: [PREF.GUNMA], region: REGION.KANTO, lat: 36.050, lng: 138.700, source: "国土地理院" },
  MITOUSAN: { id: "m227", name: "三頭山", reading: "みとうさん", elevation: 1531, prefectures: [PREF.TOKYO, PREF.YAMANASHI], region: REGION.KANTO, lat: 35.730, lng: 139.000, source: "国土地理院" },
  OOYAMA: { id: "m228", name: "大山（丹沢）", aliases: ["大山"], reading: "おおやま", elevation: 1252, prefectures: [PREF.KANAGAWA], region: REGION.KANTO, lat: 35.440, lng: 139.230, source: "国土地理院" },
  KINTOKIYAMA: { id: "m229", name: "金時山", reading: "きんときやま", elevation: 1212, prefectures: [PREF.KANAGAWA, PREF.SHIZUOKA], region: REGION.KANTO, lat: 35.280, lng: 139.000, source: "国土地理院" },
  HAKONEYAMA: { id: "m230", name: "箱根山", reading: "はこねやま", elevation: 1438, prefectures: [PREF.KANAGAWA], region: REGION.KANTO, lat: 35.230, lng: 139.020, source: "国土地理院" },
  KINPOKUSAN: { id: "m231", name: "金北山", reading: "きんぽくさん", elevation: 1172, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 38.100, lng: 138.400, source: "国土地理院" },
  AWAGATAKE: { id: "m232", name: "粟ヶ岳", reading: "あわがたけ", elevation: 1293, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.550, lng: 139.150, source: "国土地理院" },
  ASAKUSADAKE: { id: "m233", name: "浅草岳", reading: "あさくさだけ", elevation: 1585, prefectures: [PREF.NIIGATA, PREF.FUKUSHIMA], region: REGION.JOSHINETSU, lat: 37.270, lng: 139.180, source: "国土地理院" },
  YONEYAMA: { id: "m234", name: "米山", reading: "よねやま", elevation: 993, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.320, lng: 138.500, source: "国土地理院" },
  YOKOTEYAMA: { id: "m235", name: "横手山", reading: "よこてやま", elevation: 2307, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.680, lng: 138.500, source: "国土地理院" },
  KASAGATAKE_NAGANO: { id: "m236", name: "笠ヶ岳（信州）", aliases: ["笠ヶ岳"], reading: "かさがたけ", elevation: 2076, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.700, lng: 138.510, source: "国土地理院" },
  MADARAOYAMA: { id: "m237", name: "斑尾山", reading: "まだらおやま", elevation: 1382, prefectures: [PREF.NAGANO, PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 36.780, lng: 138.200, source: "国土地理院" },
  YAKEYAMA: { id: "m238", name: "焼山", reading: "やけやま", elevation: 2400, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 36.920, lng: 138.040, source: "国土地理院" },
  KUROHIMEYAMA_NIIGATA: { id: "m239", name: "黒姫山（頸城）", aliases: ["黒姫山"], reading: "くろひめやま", elevation: 1221, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.020, lng: 137.920, source: "国土地理院" },
  HACHIBUSEYAMA: { id: "m240", name: "鉢伏山", reading: "はちぶせやま", elevation: 1929, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.130, lng: 138.050, source: "国土地理院" },
  NYUUKASAYAMA: { id: "m241", name: "入笠山", reading: "にゅうかさやま", elevation: 1955, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 35.900, lng: 138.180, source: "国土地理院" },
  KOKUSHIGATAKE: { id: "m242", name: "国師ヶ岳", reading: "こくしがたけ", elevation: 2592, prefectures: [PREF.YAMANASHI, PREF.NAGANO], region: REGION.CHUBU, lat: 35.850, lng: 138.620, source: "国土地理院" },
  KURODAKE_YAMANASHI: { id: "m243", name: "黒岳（御坂）", aliases: ["黒岳"], reading: "くろだけ", elevation: 1793, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.550, lng: 138.780, source: "国土地理院" },
  ASAHIDAKE_TOYAMA: { id: "m244", name: "朝日岳（白馬）", aliases: ["朝日岳"], reading: "あさひだけ", elevation: 2418, prefectures: [PREF.TOYAMA, PREF.NIIGATA], region: REGION.KITA_ALPS, lat: 36.820, lng: 137.750, source: "国土地理院" },
  KARAMATSUDAKE: { id: "m245", name: "唐松岳", reading: "からまつだけ", elevation: 2696, prefectures: [PREF.NAGANO, PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.700, lng: 137.750, source: "国土地理院" },
  JIIGATAKE: { id: "m246", name: "爺ヶ岳", reading: "じいがたけ", elevation: 2670, prefectures: [PREF.NAGANO, PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.600, lng: 137.730, source: "国土地理院" },
  RENGEDAKE: { id: "m247", name: "蓮華岳", reading: "れんげだけ", elevation: 2799, prefectures: [PREF.NAGANO, PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.550, lng: 137.660, source: "国土地理院" },
  KUWASAKIYAMA: { id: "m248", name: "鍬崎山", reading: "くわさきやま", elevation: 2090, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.550, lng: 137.550, source: "国土地理院" },
  NOGUCHIGOROUDAKE: { id: "m249", name: "野口五郎岳", reading: "のぐちごろうだけ", elevation: 2924, prefectures: [PREF.TOYAMA, PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.450, lng: 137.620, source: "国土地理院" },
  MITSUMATARENGEDAKE: { id: "m250", name: "三俣蓮華岳", reading: "みつまたれんげだけ", elevation: 2841, prefectures: [PREF.TOYAMA, PREF.NAGANO, PREF.GIFU], region: REGION.KITA_ALPS, lat: 36.400, lng: 137.600, source: "国土地理院" },
  HACHIMORIYAMA: { id: "m251", name: "鉢盛山", reading: "はちもりやま", elevation: 2447, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.050, lng: 137.700, source: "国土地理院" },
  KOSUMOYAMA: { id: "m252", name: "越百山", reading: "こすもやま", elevation: 2614, prefectures: [PREF.NAGANO], region: REGION.CHUO_ALPS, lat: 35.650, lng: 137.800, source: "国土地理院" },
  NAGISODAKE: { id: "m253", name: "南木曽岳", reading: "なぎそだけ", elevation: 1679, prefectures: [PREF.NAGANO], region: REGION.CHUO_ALPS, lat: 35.600, lng: 137.620, source: "国土地理院" },
  OKUSANKAIDAKE: { id: "m254", name: "奥三界岳", reading: "おくさんかいだけ", elevation: 1811, prefectures: [PREF.NAGANO, PREF.GIFU], region: REGION.CHUBU, lat: 35.600, lng: 137.500, source: "国土地理院" },
  ASAYOMINE: { id: "m255", name: "アサヨ峰", reading: "あさよみね", elevation: 2799, prefectures: [PREF.YAMANASHI], region: REGION.MINAMI_ALPS, lat: 35.700, lng: 138.270, source: "国土地理院" },
  OKUCHYAUSUYAMA: { id: "m256", name: "奥茶臼山", reading: "おくちゃうすやま", elevation: 2474, prefectures: [PREF.NAGANO], region: REGION.MINAMI_ALPS, lat: 35.430, lng: 138.080, source: "国土地理院" },
  CHYAUSUDAKE: { id: "m257", name: "茶臼岳", reading: "ちゃうすだけ", elevation: 2604, prefectures: [PREF.SHIZUOKA, PREF.NAGANO], region: REGION.MINAMI_ALPS, lat: 35.380, lng: 138.100, source: "国土地理院" },
  YANBUSHI: { id: "m258", name: "山伏", reading: "やんぶし", elevation: 2013, prefectures: [PREF.SHIZUOKA, PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.300, lng: 138.300, source: "国土地理院" },
  KUROBOUSHIDAKE: { id: "m259", name: "黒法師岳", reading: "くろぼうしだけ", elevation: 2068, prefectures: [PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.250, lng: 138.050, source: "国土地理院" },
  TAKATSUKAYAMA: { id: "m260", name: "高塚山", reading: "たかつかやま", elevation: 1621, prefectures: [PREF.SHIZUOKA], region: REGION.MINAMI_ALPS, lat: 35.180, lng: 138.080, source: "国土地理院" },
  KUMABUSHIYAMA: { id: "m261", name: "熊伏山", reading: "くまぶしやま", elevation: 1654, prefectures: [PREF.SHIZUOKA, PREF.NAGANO], region: REGION.CHUBU, lat: 35.270, lng: 137.900, source: "国土地理院" },
  SHIRAKIMINE: { id: "m262", name: "白木峰", reading: "しらきみね", elevation: 1596, prefectures: [PREF.TOYAMA, PREF.GIFU], region: REGION.CHUBU, lat: 36.450, lng: 137.100, source: "国土地理院" },
  NINGYOUYAMA: { id: "m263", name: "人形山", reading: "にんぎょうやま", elevation: 1726, prefectures: [PREF.TOYAMA, PREF.GIFU], region: REGION.CHUBU, lat: 36.350, lng: 136.950, source: "国土地理院" },
  SARUGABABAYAMA: { id: "m264", name: "猿ヶ馬場山", reading: "さるがばばやま", elevation: 1875, prefectures: [PREF.GIFU], region: REGION.CHUBU, lat: 36.250, lng: 136.900, source: "国土地理院" },
  KAOREDAKE: { id: "m265", name: "川上岳", reading: "かおれだけ", elevation: 1625, prefectures: [PREF.GIFU], region: REGION.CHUBU, lat: 36.000, lng: 137.200, source: "国土地理院" },
  WASHIGATAKE: { id: "m266", name: "鷲ヶ岳", reading: "わしがたけ", elevation: 1671, prefectures: [PREF.GIFU], region: REGION.CHUBU, lat: 36.050, lng: 136.950, source: "国土地理院" },
  IOUZEN: { id: "m267", name: "医王山", reading: "いおうぜん", elevation: 939, prefectures: [PREF.ISHIKAWA, PREF.TOYAMA], region: REGION.CHUBU, lat: 36.500, lng: 136.800, source: "国土地理院" },
  DAIMONZAN: { id: "m268", name: "大門山", reading: "だいもんざん", elevation: 1572, prefectures: [PREF.ISHIKAWA, PREF.TOYAMA], region: REGION.CHUBU, lat: 36.400, lng: 136.800, source: "国土地理院" },
  OOGASAYAMA: { id: "m269", name: "大笠山", reading: "おおがさやま", elevation: 1822, prefectures: [PREF.ISHIKAWA, PREF.TOYAMA], region: REGION.CHUBU, lat: 36.330, lng: 136.800, source: "国土地理院" },
  SANPOUIWADAKE: { id: "m270", name: "三方岩岳", reading: "さんぽういわだけ", elevation: 1736, prefectures: [PREF.ISHIKAWA, PREF.GIFU], region: REGION.CHUBU, lat: 36.290, lng: 136.770, source: "国土地理院" },
  NOBUSEGATAKE: { id: "m271", name: "野伏ヶ岳", reading: "のぶせがたけ", elevation: 1674, prefectures: [PREF.FUKUI, PREF.GIFU], region: REGION.CHUBU, lat: 35.900, lng: 136.700, source: "国土地理院" },
  KYOUGATAKE_FUKUI: { id: "m272", name: "経ヶ岳（越前）", aliases: ["経ヶ岳"], reading: "きょうがたけ", elevation: 1625, prefectures: [PREF.FUKUI], region: REGION.CHUBU, lat: 35.950, lng: 136.450, source: "国土地理院" },
  KANMURIYAMA: { id: "m273", name: "冠山", reading: "かんむりやま", elevation: 1257, prefectures: [PREF.FUKUI, PREF.GIFU], region: REGION.CHUBU, lat: 35.650, lng: 136.400, source: "国土地理院" },
  FUJIWARADAKE: { id: "m274", name: "藤原岳", reading: "ふじわらだけ", elevation: 1140, prefectures: [PREF.MIE, PREF.SHIGA], region: REGION.KINKI, lat: 35.150, lng: 136.420, source: "国土地理院" },
  KUROSOYAMA: { id: "m275", name: "倶留尊山", reading: "くろそやま", elevation: 1037, prefectures: [PREF.MIE, PREF.NARA], region: REGION.KINKI, lat: 34.530, lng: 136.150, source: "国土地理院" },
  MIUNEYAMA: { id: "m276", name: "三峰山", reading: "みうねやま", elevation: 1235, prefectures: [PREF.MIE, PREF.NARA], region: REGION.KINKI, lat: 34.420, lng: 136.200, source: "国土地理院" },
  TAKAMIYAMA: { id: "m277", name: "高見山", reading: "たかみやま", elevation: 1248, prefectures: [PREF.MIE, PREF.NARA], region: REGION.KINKI, lat: 34.430, lng: 136.100, source: "国土地理院" },
  RYUUMONGATAKE: { id: "m278", name: "龍門岳", reading: "りゅうもんがたけ", elevation: 904, prefectures: [PREF.NARA], region: REGION.KINKI, lat: 34.450, lng: 135.900, source: "国土地理院" },
  SANJYOUGATAKE: { id: "m279", name: "山上ヶ岳", reading: "さんじょうがたけ", elevation: 1719, prefectures: [PREF.NARA], region: REGION.KINKI, lat: 34.250, lng: 135.930, source: "国土地理院" },
  GOMADANZAN: { id: "m280", name: "護摩壇山", reading: "ごまだんざん", elevation: 1372, prefectures: [PREF.WAKAYAMA, PREF.NARA], region: REGION.KINKI, lat: 34.070, lng: 135.550, source: "国土地理院" },
  YAMATOKATSURAGISAN: { id: "m281", name: "大和葛城山", reading: "やまとかつらぎさん", elevation: 959, prefectures: [PREF.NARA, PREF.OSAKA], region: REGION.KINKI, lat: 34.450, lng: 135.680, source: "国土地理院" },
  HOURAISAN: { id: "m282", name: "蓬莱山", reading: "ほうらいさん", elevation: 1174, prefectures: [PREF.SHIGA], region: REGION.KINKI, lat: 35.180, lng: 135.930, source: "国土地理院" },
  HIEIZAN: { id: "m283", name: "比叡山", reading: "ひえいざん", elevation: 848, prefectures: [PREF.SHIGA, PREF.KYOTO], region: REGION.KINKI, lat: 35.070, lng: 135.830, source: "国土地理院" },
  ATAGOYAMA: { id: "m284", name: "愛宕山", reading: "あたごやま", elevation: 924, prefectures: [PREF.KYOTO], region: REGION.KINKI, lat: 35.070, lng: 135.650, source: "国土地理院" },
  ROKKOUSAN: { id: "m285", name: "六甲山", reading: "ろっこうさん", elevation: 931, prefectures: [PREF.HYOGO], region: REGION.KINKI, lat: 34.780, lng: 135.270, source: "国土地理院" },
  OUGINOSEN: { id: "m286", name: "扇ノ山", reading: "おうぎのせん", elevation: 1310, prefectures: [PREF.TOTTORI, PREF.HYOGO], region: REGION.CHUGOKU, lat: 35.450, lng: 134.450, source: "国土地理院" },
  NAGISAN: { id: "m287", name: "那岐山", reading: "なぎさん", elevation: 1255, prefectures: [PREF.OKAYAMA, PREF.TOTTORI], region: REGION.CHUGOKU, lat: 35.100, lng: 134.180, source: "国土地理院" },
  DOUGOYAMA: { id: "m288", name: "道後山", reading: "どうごやま", elevation: 1271, prefectures: [PREF.HIROSHIMA, PREF.TOTTORI], region: REGION.CHUGOKU, lat: 35.050, lng: 133.200, source: "国土地理院" },
  AZUMAYAMA_HIROSHIMA: { id: "m289", name: "吾妻山（比婆）", aliases: ["吾妻山", "比婆山"], reading: "あづまやま", elevation: 1238, prefectures: [PREF.HIROSHIMA, PREF.SHIMANE], region: REGION.CHUGOKU, lat: 35.030, lng: 133.050, source: "国土地理院" },
  IYOFUJI: { id: "m290", name: "伊予富士", reading: "いよふじ", elevation: 1756, prefectures: [PREF.EHIME, PREF.KOCHI], region: REGION.CHUGOKU, lat: 33.800, lng: 133.180, source: "国土地理院" },
  KAMEGAMORI: { id: "m291", name: "瓶ヶ森", reading: "かめがもり", elevation: 1897, prefectures: [PREF.EHIME, PREF.KOCHI], region: REGION.CHUGOKU, lat: 33.780, lng: 133.200, source: "国土地理院" },
  SANBONGUI: { id: "m292", name: "三本杭", reading: "さんぼんぐい", elevation: 1226, prefectures: [PREF.EHIME], region: REGION.CHUGOKU, lat: 33.270, lng: 132.700, source: "国土地理院" },
  SASAYAMA: { id: "m293", name: "篠山", reading: "ささやま", elevation: 1065, prefectures: [PREF.KOCHI, PREF.EHIME], region: REGION.CHUGOKU, lat: 32.950, lng: 132.650, source: "国土地理院" },
  SEFURISAN: { id: "m294", name: "脊振山", reading: "せふりさん", elevation: 1055, prefectures: [PREF.SAGA, PREF.FUKUOKA], region: REGION.KYUSHU, lat: 33.430, lng: 130.370, source: "国土地理院" },
  TSURUMIDAKE: { id: "m295", name: "鶴見岳", reading: "つるみだけ", elevation: 1375, prefectures: [PREF.OITA], region: REGION.KYUSHU, lat: 33.280, lng: 131.430, source: "国土地理院" },
  WAITASAN: { id: "m296", name: "涌蓋山", reading: "わいたさん", elevation: 1500, prefectures: [PREF.OITA, PREF.KUMAMOTO], region: REGION.KYUSHU, lat: 33.130, lng: 131.180, source: "国土地理院" },
  TAISENZAN: { id: "m297", name: "大船山", reading: "たいせんざん", elevation: 1786, prefectures: [PREF.OITA], region: REGION.KYUSHU, lat: 33.080, lng: 131.270, source: "国土地理院" },
  KATAMUKIYAMA: { id: "m298", name: "傾山", reading: "かたむきやま", elevation: 1605, prefectures: [PREF.OITA, PREF.MIYAZAKI], region: REGION.KYUSHU, lat: 32.830, lng: 131.450, source: "国土地理院" },
  TARADAKE: { id: "m299", name: "多良岳", reading: "たらだけ", elevation: 996, prefectures: [PREF.SAGA, PREF.NAGASAKI], region: REGION.KYUSHU, lat: 33.000, lng: 130.100, source: "国土地理院" },
  KUNIMIDAKE: { id: "m300", name: "国見岳", reading: "くにみだけ", elevation: 1739, prefectures: [PREF.KUMAMOTO, PREF.MIYAZAKI], region: REGION.KYUSHU, lat: 32.580, lng: 131.100, source: "国土地理院" },
  TAKAKUMAYAMA: { id: "m301", name: "高隈山", reading: "たかくまやま", elevation: 1236, prefectures: [PREF.KAGOSHIMA], region: REGION.KYUSHU, lat: 31.500, lng: 130.850, source: "国土地理院" },

  // ── 花の百名山 / 新・花の百名山 固有分（田中澄江選 / m302..） ──
  // 山のほか高原・湿原・沼など花の名所も含む。標高・lat/lng は代表値（要精査）。
  TAKAOSAN: { id: "m302", name: "高尾山", reading: "たかおさん", elevation: 599, prefectures: [PREF.TOKYO], region: REGION.KANTO, lat: 35.625, lng: 139.244, source: "代表値" },
  OOGUSUYAMA: { id: "m303", name: "大楠山", reading: "おおぐすやま", elevation: 241, prefectures: [PREF.KANAGAWA], region: REGION.KANTO, lat: 35.220, lng: 139.620, source: "代表値" },
  GOZENYAMA: { id: "m304", name: "御前山", reading: "ごぜんやま", elevation: 1405, prefectures: [PREF.TOKYO], region: REGION.KANTO, lat: 35.830, lng: 139.100, source: "代表値" },
  MAKUYAMA: { id: "m305", name: "幕山", reading: "まくやま", elevation: 625, prefectures: [PREF.KANAGAWA], region: REGION.KANTO, lat: 35.160, lng: 139.100, source: "代表値" },
  TAKASUZUYAMA: { id: "m306", name: "高鈴山", reading: "たかすずやま", elevation: 623, prefectures: [PREF.IBARAKI], region: REGION.KANTO, lat: 36.600, lng: 140.620, source: "代表値" },
  MISUJIYAMA: { id: "m307", name: "三筋山", reading: "みすじやま", elevation: 812, prefectures: [PREF.SHIZUOKA], region: REGION.CHUBU, lat: 34.780, lng: 139.050, source: "代表値" },
  KAWANORIYAMA: { id: "m308", name: "川苔山", reading: "かわのりやま", elevation: 1363, prefectures: [PREF.TOKYO], region: REGION.KANTO, lat: 35.830, lng: 139.150, source: "代表値" },
  JIZOUDAKE: { id: "m309", name: "地蔵岳（赤城）", aliases: ["地蔵岳"], reading: "じぞうだけ", elevation: 1674, prefectures: [PREF.GUNMA], region: REGION.KANTO, lat: 36.550, lng: 139.180, source: "代表値" },
  TAKAMIZUSAN: { id: "m310", name: "高水山", reading: "たかみずさん", elevation: 759, prefectures: [PREF.TOKYO], region: REGION.KANTO, lat: 35.830, lng: 139.180, source: "代表値" },
  MITAKESAN: { id: "m311", name: "御岳山", aliases: ["武州御岳山"], reading: "みたけさん", elevation: 929, prefectures: [PREF.TOKYO], region: REGION.KANTO, lat: 35.780, lng: 139.150, source: "代表値" },
  SHYOUTOUSAN: { id: "m312", name: "生藤山", reading: "しょうとうさん", elevation: 990, prefectures: [PREF.TOKYO, PREF.KANAGAWA], region: REGION.KANTO, lat: 35.660, lng: 139.100, source: "代表値" },
  ISHIWARIYAMA: { id: "m313", name: "石割山", reading: "いしわりやま", elevation: 1413, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.450, lng: 138.920, source: "代表値" },
  OZENUMA: { id: "m314", name: "尾瀬沼", reading: "おぜぬま", elevation: 1665, prefectures: [PREF.FUKUSHIMA, PREF.GUNMA], region: REGION.JOSHINETSU, lat: 36.920, lng: 139.300, source: "代表値" },
  KAMAKURADAKE: { id: "m315", name: "鎌倉岳", reading: "かまくらだけ", elevation: 967, prefectures: [PREF.FUKUSHIMA], region: REGION.TOHOKU, lat: 37.400, lng: 140.650, source: "代表値" },
  TASHIROYAMA: { id: "m316", name: "田代山", reading: "たしろやま", elevation: 1971, prefectures: [PREF.FUKUSHIMA, PREF.TOCHIGI], region: REGION.TOHOKU, lat: 36.950, lng: 139.450, source: "代表値" },
  HAGUROSAN: { id: "m317", name: "羽黒山", reading: "はぐろさん", elevation: 414, prefectures: [PREF.YAMAGATA], region: REGION.TOHOKU, lat: 38.700, lng: 139.970, source: "代表値" },
  REBUNDAKE: { id: "m318", name: "礼文岳", reading: "れぶんだけ", elevation: 490, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 45.370, lng: 141.030, source: "代表値" },
  APOIDAKE: { id: "m319", name: "アポイ岳", reading: "あぽいだけ", elevation: 811, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.100, lng: 143.020, source: "代表値" },
  FURANODAKE: { id: "m320", name: "富良野岳", reading: "ふらのだけ", elevation: 1912, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.420, lng: 142.670, source: "代表値" },
  NUMANOTAIRA: { id: "m321", name: "沼ノ平", reading: "ぬまのたいら", elevation: 1450, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.700, lng: 142.850, source: "代表値" },
  SORANUMADAKE: { id: "m322", name: "空沼岳", reading: "そらぬまだけ", elevation: 1251, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.900, lng: 141.200, source: "代表値" },
  URYUUNUMA: { id: "m323", name: "雨竜沼", reading: "うりゅうぬま", elevation: 840, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.700, lng: 141.700, source: "代表値" },
  IMOUSHITSUGEN: { id: "m324", name: "葦毛湿原", reading: "いもうしつげん", elevation: 63, prefectures: [PREF.AICHI], region: REGION.CHUBU, lat: 34.730, lng: 137.450, source: "代表値" },
  GOSHIKIGAHARA: { id: "m325", name: "五色ヶ原", reading: "ごしきがはら", elevation: 2490, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.550, lng: 137.580, source: "代表値" },
  YUMIORIDAKE: { id: "m326", name: "弓折岳", reading: "ゆみおりだけ", elevation: 2592, prefectures: [PREF.GIFU], region: REGION.KITA_ALPS, lat: 36.350, lng: 137.580, source: "代表値" },
  SUGOROKUDAKE: { id: "m327", name: "双六岳", reading: "すごろくだけ", elevation: 2860, prefectures: [PREF.GIFU, PREF.NAGANO], region: REGION.KITA_ALPS, lat: 36.370, lng: 137.600, source: "代表値" },
  NEKODAKE: { id: "m328", name: "根子岳", reading: "ねこだけ", elevation: 2207, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.500, lng: 138.400, source: "代表値" },
  KIRINOTOU: { id: "m329", name: "霧ノ塔", reading: "きりのとう", elevation: 1994, prefectures: [PREF.NIIGATA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.850, lng: 138.700, source: "代表値" },
  MORIYASAN: { id: "m330", name: "守屋山", reading: "もりやさん", elevation: 1650, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 35.950, lng: 138.100, source: "代表値" },
  KUROFUYAMA: { id: "m331", name: "黒斑山", reading: "くろふやま", elevation: 2404, prefectures: [PREF.GUNMA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.410, lng: 138.500, source: "代表値" },
  SHIMAGAREYAMA: { id: "m332", name: "縞枯山", reading: "しまがれやま", elevation: 2403, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.070, lng: 138.350, source: "代表値" },
  GOZUSAN: { id: "m333", name: "五頭山", reading: "ごずさん", elevation: 912, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.780, lng: 139.300, source: "代表値" },
  TAKAMINEYAMA: { id: "m334", name: "高峰山", reading: "たかみねやま", elevation: 2106, prefectures: [PREF.NAGANO, PREF.GUNMA], region: REGION.JOSHINETSU, lat: 36.400, lng: 138.480, source: "代表値" },
  SHIGAKOUGEN: { id: "m335", name: "志賀高原", reading: "しがこうげん", elevation: 2036, prefectures: [PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.700, lng: 138.520, source: "代表値" },
  HAMAISHIDAKE: { id: "m336", name: "浜石岳", reading: "はまいしだけ", elevation: 707, prefectures: [PREF.SHIZUOKA], region: REGION.CHUBU, lat: 35.100, lng: 138.550, source: "代表値" },
  MIKAMIYAMA: { id: "m337", name: "三上山", reading: "みかみやま", elevation: 432, prefectures: [PREF.SHIGA], region: REGION.KINKI, lat: 35.050, lng: 136.050, source: "代表値" },
  RYOUZENZAN: { id: "m338", name: "霊仙山", reading: "りょうぜんざん", elevation: 1083, prefectures: [PREF.SHIGA], region: REGION.KINKI, lat: 35.280, lng: 136.400, source: "代表値" },
  NIJYOUZAN: { id: "m339", name: "二上山", reading: "にじょうざん", elevation: 517, prefectures: [PREF.NARA, PREF.OSAKA], region: REGION.KINKI, lat: 34.520, lng: 135.680, source: "代表値" },
  OIKEDAKE: { id: "m340", name: "御池岳", reading: "おいけだけ", elevation: 1247, prefectures: [PREF.SHIGA, PREF.MIE], region: REGION.KINKI, lat: 35.180, lng: 136.420, source: "代表値" },
  TENGUKOUGEN: { id: "m341", name: "天狗高原", reading: "てんぐこうげん", elevation: 1484, prefectures: [PREF.KOCHI, PREF.EHIME], region: REGION.CHUGOKU, lat: 33.480, lng: 132.920, source: "代表値" },
  YOKOGURAYAMA: { id: "m342", name: "横倉山", reading: "よこぐらやま", elevation: 793, prefectures: [PREF.KOCHI], region: REGION.CHUGOKU, lat: 33.550, lng: 133.100, source: "代表値" },
  MARUSASAYAMA: { id: "m343", name: "丸笹山", reading: "まるささやま", elevation: 1712, prefectures: [PREF.TOKUSHIMA], region: REGION.CHUGOKU, lat: 33.870, lng: 134.100, source: "代表値" },
  MEKUNNAIDAKE: { id: "m344", name: "目国内岳", reading: "めくんないだけ", elevation: 1220, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.880, lng: 140.580, source: "代表値" },
  OROFUREYAMA: { id: "m345", name: "オロフレ山", reading: "おろふれやま", elevation: 1230, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.550, lng: 141.050, source: "代表値" },
  MURORANDAKE: { id: "m346", name: "室蘭岳", aliases: ["鷲別岳"], reading: "むろらんだけ", elevation: 911, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 42.400, lng: 140.950, source: "代表値" },
  HAKUUNZAN: { id: "m347", name: "白雲山", reading: "はくうんざん", elevation: 1186, prefectures: [PREF.HOKKAIDO], region: REGION.HOKKAIDO, lat: 43.300, lng: 143.180, source: "代表値" },
  TANEYAMAKOUGEN: { id: "m348", name: "種山高原", reading: "たねやまこうげん", elevation: 870, prefectures: [PREF.IWATE], region: REGION.TOHOKU, lat: 39.150, lng: 141.450, source: "代表値" },
  NARUKAMIYAMA: { id: "m349", name: "鳴神山", reading: "なるかみやま", elevation: 980, prefectures: [PREF.GUNMA], region: REGION.KANTO, lat: 36.450, lng: 139.300, source: "代表値" },
  OZAKUSAN: { id: "m350", name: "石裂山", reading: "おざくさん", elevation: 879, prefectures: [PREF.TOCHIGI], region: REGION.KANTO, lat: 36.620, lng: 139.650, source: "代表値" },
  MIKAMOYAMA: { id: "m351", name: "三毳山", reading: "みかもやま", elevation: 229, prefectures: [PREF.TOCHIGI], region: REGION.KANTO, lat: 36.350, lng: 139.650, source: "代表値" },
  IZUGATAKE: { id: "m352", name: "伊豆ヶ岳", reading: "いずがたけ", elevation: 851, prefectures: [PREF.SAITAMA], region: REGION.KANTO, lat: 35.930, lng: 139.180, source: "代表値" },
  HIRYUUYAMA: { id: "m353", name: "飛龍山", reading: "ひりゅうやま", elevation: 2077, prefectures: [PREF.SAITAMA, PREF.YAMANASHI], region: REGION.KANTO, lat: 35.850, lng: 138.880, source: "代表値" },
  KASATORIYAMA: { id: "m354", name: "笠取山", reading: "かさとりやま", elevation: 1953, prefectures: [PREF.SAITAMA, PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.880, lng: 138.830, source: "代表値" },
  OTOMEKOUGEN: { id: "m355", name: "乙女高原", reading: "おとめこうげん", elevation: 1700, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.730, lng: 138.650, source: "代表値" },
  KUKIYAMA: { id: "m356", name: "九鬼山", reading: "くきやま", elevation: 970, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.580, lng: 138.950, source: "代表値" },
  NIJYUUROKUYASAN: { id: "m357", name: "二十六夜山", reading: "にじゅうろくやさん", elevation: 972, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.550, lng: 138.900, source: "代表値" },
  KUROFUJI: { id: "m358", name: "黒富士", reading: "くろふじ", elevation: 1633, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.720, lng: 138.550, source: "代表値" },
  TENGUYAMA: { id: "m359", name: "天狗山", reading: "てんぐやま", elevation: 1882, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.000, lng: 138.550, source: "代表値" },
  GONGENYAMA: { id: "m360", name: "権現山", reading: "ごんげんやま", elevation: 1312, prefectures: [PREF.YAMANASHI], region: REGION.CHUBU, lat: 35.620, lng: 138.850, source: "代表値" },
  CHYOUKUROUYAMA: { id: "m361", name: "長九郎山", reading: "ちょうくろうやま", elevation: 996, prefectures: [PREF.SHIZUOKA], region: REGION.CHUBU, lat: 34.750, lng: 138.850, source: "代表値" },
  KAZAKOSHIYAMA: { id: "m362", name: "風越山", reading: "かざこしやま", elevation: 1535, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 35.500, lng: 137.780, source: "代表値" },
  ODAKAYAMA: { id: "m363", name: "尾高山", reading: "おだかやま", elevation: 2212, prefectures: [PREF.NAGANO], region: REGION.MINAMI_ALPS, lat: 35.400, lng: 138.050, source: "代表値" },
  YASHIMAGAHARASHITSUGEN: { id: "m364", name: "八島ヶ原湿原", reading: "やしまがはらしつげん", elevation: 1646, prefectures: [PREF.NAGANO], region: REGION.CHUBU, lat: 36.100, lng: 138.180, source: "代表値" },
  HOKUSHINGOGAKU: { id: "m365", name: "北信五岳", reading: "ほくしんごがく", elevation: 2446, prefectures: [PREF.NAGANO, PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 36.800, lng: 138.100, source: "代表値" },
  KOMATSUBARASHITSUGEN: { id: "m366", name: "小松原湿原", reading: "こまつばらしつげん", elevation: 2145, prefectures: [PREF.NIIGATA, PREF.NAGANO], region: REGION.JOSHINETSU, lat: 36.850, lng: 138.680, source: "代表値" },
  HIGURAYAMA: { id: "m367", name: "日倉山", reading: "ひぐらやま", elevation: 844, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.600, lng: 139.450, source: "代表値" },
  KAKUDAYAMA: { id: "m368", name: "角田山", reading: "かくだやま", elevation: 482, prefectures: [PREF.NIIGATA], region: REGION.JOSHINETSU, lat: 37.850, lng: 138.800, source: "代表値" },
  TAROBEEDAIRA: { id: "m369", name: "太郎兵衛平", reading: "たろべえだいら", elevation: 2330, prefectures: [PREF.TOYAMA], region: REGION.KITA_ALPS, lat: 36.450, lng: 137.550, source: "代表値" },
  KITANOMATADAKE: { id: "m370", name: "北ノ俣岳", aliases: ["上ノ岳"], reading: "きたのまただけ", elevation: 2662, prefectures: [PREF.TOYAMA, PREF.GIFU], region: REGION.KITA_ALPS, lat: 36.420, lng: 137.550, source: "代表値" },
  YUMIHARISANCHI: { id: "m371", name: "弓張山地", reading: "ゆみはりさんち", elevation: 325, prefectures: [PREF.AICHI, PREF.SHIZUOKA], region: REGION.CHUBU, lat: 34.720, lng: 137.550, source: "代表値" },
  SANAGEYAMA: { id: "m372", name: "猿投山", reading: "さなげやま", elevation: 629, prefectures: [PREF.AICHI], region: REGION.CHUBU, lat: 35.180, lng: 137.170, source: "代表値" },
  KUMANOJI: { id: "m373", name: "熊野路", reading: "くまのじ", elevation: 546, prefectures: [PREF.WAKAYAMA, PREF.NARA, PREF.MIE], region: REGION.KINKI, lat: 33.900, lng: 135.800, source: "代表値" },
  HIYAMIZUYAMA: { id: "m374", name: "冷水山", reading: "ひやみずやま", elevation: 1262, prefectures: [PREF.WAKAYAMA, PREF.NARA], region: REGION.KINKI, lat: 34.050, lng: 135.550, source: "代表値" },
  ODANIYAMA: { id: "m375", name: "小谷山", reading: "おだにやま", elevation: 495, prefectures: [PREF.SHIGA], region: REGION.KINKI, lat: 35.500, lng: 136.280, source: "代表値" },
  OOEYAMA: { id: "m376", name: "大江山", reading: "おおえやま", elevation: 833, prefectures: [PREF.KYOTO], region: REGION.KINKI, lat: 35.450, lng: 135.100, source: "代表値" },
  SENJYOUSAN: { id: "m377", name: "船上山", reading: "せんじょうさん", elevation: 687, prefectures: [PREF.TOTTORI], region: REGION.CHUGOKU, lat: 35.400, lng: 133.550, source: "代表値" },
  BESSHIDOUZANGOE: { id: "m378", name: "別子銅山越", reading: "べっしどうざんごえ", elevation: 1294, prefectures: [PREF.EHIME], region: REGION.CHUGOKU, lat: 33.870, lng: 133.300, source: "代表値" },
  KOSHYOSAN: { id: "m379", name: "古処山", reading: "こしょさん", elevation: 859, prefectures: [PREF.FUKUOKA], region: REGION.KYUSHU, lat: 33.500, lng: 130.750, source: "代表値" },
};

// Node.js（バリデータ）からも参照できるようにする
// 配列ビュー（描画・反復用）
const MOUNTAIN_CATALOG = Object.values(MOUNTAIN);

if (typeof module !== "undefined" && module.exports) {
  module.exports = { MOUNTAIN, MOUNTAIN_CATALOG };
}