// 自動運転実証実験マップ スキーマ定義
// UMD形式: ブラウザ（グローバル変数）と Node.js（module.exports）の両方で動作する
//
// 設計方針:
//   - data.js は必ずこのファイルの定数を参照する（文字列リテラルで enum 値を書かない）
//   - タイポすると undefined になりバリデーションで即検出される
//   - 表示ラベルの変更はここ1箇所のみ

(function (exports) {

  // ─────────────────────────────────────────────
  // STATUS: 実験ステータス
  // ─────────────────────────────────────────────
  const STATUS = {
    ACTIVE:         { id: "active",         label: "実施中" },
    COMPLETED:      { id: "completed",      label: "完了" },
    PLANNED:        { id: "planned",        label: "計画中" },
    ACTIVE_PLANNED: { id: "active-planned", label: "実施中・一部計画中" },
    ACTIVE_DEV:     { id: "active-dev",     label: "実施中・開発中" },
    CANCELLED:      { id: "cancelled",      label: "中止" },
  };

  // ─────────────────────────────────────────────
  // PREF: 都道府県（47都道府県）
  // ─────────────────────────────────────────────
  const PREF = {
    HOKKAIDO:  { id: "hokkaido",  label: "北海道" },
    AOMORI:    { id: "aomori",    label: "青森県" },
    IWATE:     { id: "iwate",     label: "岩手県" },
    MIYAGI:    { id: "miyagi",    label: "宮城県" },
    AKITA:     { id: "akita",     label: "秋田県" },
    YAMAGATA:  { id: "yamagata",  label: "山形県" },
    FUKUSHIMA: { id: "fukushima", label: "福島県" },
    IBARAKI:   { id: "ibaraki",   label: "茨城県" },
    TOCHIGI:   { id: "tochigi",   label: "栃木県" },
    GUNMA:     { id: "gunma",     label: "群馬県" },
    SAITAMA:   { id: "saitama",   label: "埼玉県" },
    CHIBA:     { id: "chiba",     label: "千葉県" },
    TOKYO:     { id: "tokyo",     label: "東京都" },
    KANAGAWA:  { id: "kanagawa",  label: "神奈川県" },
    NIIGATA:   { id: "niigata",   label: "新潟県" },
    TOYAMA:    { id: "toyama",    label: "富山県" },
    ISHIKAWA:  { id: "ishikawa",  label: "石川県" },
    FUKUI:     { id: "fukui",     label: "福井県" },
    YAMANASHI: { id: "yamanashi", label: "山梨県" },
    NAGANO:    { id: "nagano",    label: "長野県" },
    GIFU:      { id: "gifu",      label: "岐阜県" },
    SHIZUOKA:  { id: "shizuoka",  label: "静岡県" },
    AICHI:     { id: "aichi",     label: "愛知県" },
    MIE:       { id: "mie",       label: "三重県" },
    SHIGA:     { id: "shiga",     label: "滋賀県" },
    KYOTO:     { id: "kyoto",     label: "京都府" },
    OSAKA:     { id: "osaka",     label: "大阪府" },
    HYOGO:     { id: "hyogo",     label: "兵庫県" },
    NARA:      { id: "nara",      label: "奈良県" },
    WAKAYAMA:  { id: "wakayama",  label: "和歌山県" },
    TOTTORI:   { id: "tottori",   label: "鳥取県" },
    SHIMANE:   { id: "shimane",   label: "島根県" },
    OKAYAMA:   { id: "okayama",   label: "岡山県" },
    HIROSHIMA: { id: "hiroshima", label: "広島県" },
    YAMAGUCHI: { id: "yamaguchi", label: "山口県" },
    TOKUSHIMA: { id: "tokushima", label: "徳島県" },
    KAGAWA:    { id: "kagawa",    label: "香川県" },
    EHIME:     { id: "ehime",     label: "愛媛県" },
    KOCHI:     { id: "kochi",     label: "高知県" },
    FUKUOKA:   { id: "fukuoka",   label: "福岡県" },
    SAGA:      { id: "saga",      label: "佐賀県" },
    NAGASAKI:  { id: "nagasaki",  label: "長崎県" },
    KUMAMOTO:  { id: "kumamoto",  label: "熊本県" },
    OITA:      { id: "oita",      label: "大分県" },
    MIYAZAKI:  { id: "miyazaki",  label: "宮崎県" },
    KAGOSHIMA: { id: "kagoshima", label: "鹿児島県" },
    OKINAWA:   { id: "okinawa",   label: "沖縄県" },
  };

  // ─────────────────────────────────────────────
  // VEH: 使用車両
  // 表記ゆれ防止のため data.js の vehicle.value は必ずここから参照する
  // 専用設計型AD車両（purpose-built）: 車両メーカー名を ADS にも設定する
  // 市販車ベース改造: 市販車名を VEH、ADシステム提供会社を ADS に設定する
  // ─────────────────────────────────────────────
  const VEH = {
    // Auve Tech
    AUVE_TECH_MICA:         { id: "auve-tech-mica",         label: "Auve Tech MiCa" },
    // BYD
    BYD_J6:                 { id: "byd-j6",                 label: "BYD J6" },
    BYD_K8:                 { id: "byd-k8",                 label: "BYD K8" },
    // Cruise
    CRUISE_ORIGIN:          { id: "cruise-origin",          label: "Cruise Origin" },
    // EVモーターズ・ジャパン
    EV_MOTORS_JAPAN_F8_MINI:{ id: "ev-motors-japan-f8-mini",label: "EVモーターズ・ジャパン F8 series4-Mini Bus" },
    EV_MOTORS_JAPAN_F8_CITY:{ id: "ev-motors-japan-f8-city",label: "EVモーターズ・ジャパン F8シリーズ2" },
    // Hyundai
    HYUNDAI_IONIQ5:         { id: "hyundai-ioniq5",         label: "Hyundai IONIQ5" },
    // いすゞ
    ISUZU_ERGA:             { id: "isuzu-erga",             label: "いすゞ エルガ" },
    ISUZU_ERGA_EV:          { id: "isuzu-erga-ev",          label: "いすゞ エルガEV" },
    ISUZU_ERGA_MIO:         { id: "isuzu-erga-mio",         label: "いすゞ エルガミオ" },
    ISUZU_ERGA_DUO:         { id: "isuzu-erga-duo",         label: "いすゞ エルガデュオ" },
    ISUZU_GIGA:             { id: "isuzu-giga",             label: "いすゞ ギガ" },
    // Jaguar
    JAGUAR_I_PACE:          { id: "jaguar-i-pace",          label: "Jaguar I-PACE" },
    // 三菱ふそう
    MITSUBISHI_SUPER_GREAT: { id: "mitsubishi-super-great", label: "三菱ふそう スーパーグレート" },
    MITSUBISHI_AERO_ACE:    { id: "mitsubishi-aero-ace",    label: "三菱ふそう エアロエース" },
    // NAVYA
    NAVYA_ARMA:             { id: "navya-arma",             label: "NAVYA ARMA" },
    NAVYA_EVO:              { id: "navya-evo",              label: "NAVYA EVO" },
    // 日産
    NISSAN_LEAF:            { id: "nissan-leaf",            label: "日産リーフ" },
    NISSAN_SERENA:          { id: "nissan-serena",          label: "日産セレナ" },
    // パナソニック
    PANASONIC_ELECTRIC_CART:{ id: "panasonic-electric-cart",label: "パナソニック製電動カート" },
    // PIX Moving
    PIX_ROBOBUS:            { id: "pix-robobus",            label: "PIX RoboBus" },
    // スズキ
    SUZUKI_SOLIO:           { id: "suzuki-solio",           label: "スズキ ソリオ" },
    // タジマモーターコーポレーション
    TAJIMA_GSM8:            { id: "tajima-gsm8",            label: "タジマ GSM8" },
    TAJIMA_NAO6J:           { id: "tajima-nao6j",           label: "タジマ NAO-6J" },
    TAJIMA_ECOM10:          { id: "tajima-ecom10",          label: "タジマ eCOM-10" },
    // トヨタ
    E_PALETTE:              { id: "e-palette",              label: "e-Palette" },
    TOYOTA_ALPHARD:         { id: "toyota-alphard",         label: "トヨタ アルファード" },
    TOYOTA_VELLFIRE:        { id: "toyota-vellfire",        label: "トヨタ ヴェルファイア" },
    TOYOTA_SIENNA:          { id: "toyota-sienna",          label: "トヨタ シエナ" },
    TOYOTA_ESTIMA:          { id: "toyota-estima",          label: "トヨタ エスティマ" },
    TOYOTA_JPN_TAXI:        { id: "toyota-jpn-taxi",        label: "トヨタ JPN TAXI" },
    // UDトラックス
    UD_QUON:                { id: "ud-quon",                label: "UDトラックス クオン" },
    // WeRide
    WERIDE_BUS:             { id: "weride-bus",             label: "WeRideバス" },
    // ヤマハ発動機
    HAKOBUS:                { id: "hakobus",                label: "HAKOBUS" },
    YAMAHA_AR07:            { id: "yamaha-ar07",            label: "ヤマハ AR-07" },
    YAMAHA_AR05:            { id: "yamaha-ar05",            label: "ヤマハ AR-05" },
    YAMAHA_AR04:            { id: "yamaha-ar04",            label: "ヤマハ AR-04" },
    YAMAHA_G30S:            { id: "yamaha-g30s",            label: "ヤマハ G30s" },
    // 日野
    HINO_PONCHO:            { id: "hino-poncho",            label: "日野ポンチョ" },
    HINO_RAINBOW:           { id: "hino-rainbow",           label: "日野レインボー" },
    HINO_RAINBOW_II:        { id: "hino-rainbow-ii",        label: "日野レインボーII" },
    HINO_BLUE_RIBBON:       { id: "hino-blue-ribbon",       label: "日野ブルーリボン" },
    HINO_LIESSE:            { id: "hino-liesse",            label: "日野リエッセ" },
    HINO_PROFIA:            { id: "hino-profia",            label: "日野プロフィア" },
    // 宇通バス（中国）
    YUTONG_XIAOYU_2:        { id: "yutong-xiaoyu-2",        label: "Yutong Xiaoyu 2.0" },
    // その他
    E_CITY_L6:              { id: "e-city-l6",              label: "E-City L6" },
    DENA_SMALL_BUS_TYPE:    { id: "dena-small-bus-type",    label: "DeNA小型バスタイプ" },
    DELIVERY_ROBOT:         { id: "delivery-robot",         label: "自動配送ロボット" },
    LARGE_ROUTE_BUS_GENERIC:{ id: "large-route-bus-generic",label: "大型路線バス" },
    SPECIAL_EQUIPMENT_VEHICLE:{ id: "special-equipment-vehicle", label: "特別装置自動車（ハンドル・ペダルなし）" },
    UNKNOWN:                { id: "unknown-vehicle",        label: "詳細不明" },
  };

  // ─────────────────────────────────────────────
  // ADS: 自動運転システム（開発・提供会社名）
  // 専用設計型AD車両（NAVYA、Auve Tech 等）もメーカー名を記載する
  // ─────────────────────────────────────────────
  const ADS = {
    // 専用設計型AD車両メーカー
    NAVYA:            { id: "navya",             label: "NAVYA" },
    AUVE_TECH:        { id: "auve-tech",         label: "Auve Tech" },
    CRUISE:           { id: "cruise",            label: "Cruise" },
    PIX_MOVING:       { id: "pix-moving",        label: "PIX Moving" },
    WERIDE:           { id: "weride",            label: "WeRide" },
    // AD技術専業・スタートアップ系
    ADVANCED_MOBILITY:{ id: "advanced-mobility", label: "先進モビリティ" },
    TIER_IV:          { id: "tier-iv",           label: "ティアフォー" },
    ZMP:              { id: "zmp",               label: "ZMP" },
    A_DRIVE:          { id: "a-drive",           label: "A-Drive" },
    A2Z:              { id: "a2z",               label: "a2z" },
    MAY_MOBILITY:     { id: "may-mobility",      label: "May Mobility" },
    WAYMO:            { id: "waymo",             label: "Waymo" },
    WAYVE:            { id: "wayve",             label: "Wayve" },
    NIHON_MOBILITY:   { id: "nihon-mobility",    label: "日本モビリティ" },
    AISANTEC:         { id: "aisantec",          label: "アイサンテクノロジー" },
    MOVEEZ:           { id: "moveez",            label: "MoveEz" },
    // 大学・研究機関系
    SAITAMA_UNIV:     { id: "saitama-univ",      label: "埼玉工業大学" },
    MEIJI_MIAD:       { id: "meiji-miad",        label: "明治大学 自動運転社会総合研究所" },
    NAGOYA_UNIV:      { id: "nagoya-univ",       label: "名古屋大学" },
    GUNMA_UNIV:       { id: "gunma-univ",        label: "群馬大学" },
    AIST:             { id: "aist",              label: "産総研" },
    // 自動車メーカー（自社AD開発）
    NISSAN:           { id: "nissan",            label: "日産" },
    SUZUKI:           { id: "suzuki",            label: "スズキ" },
    UD_TRUCKS:        { id: "ud-trucks",         label: "UDトラックス" },
    YAMAHA:           { id: "yamaha",            label: "ヤマハ発動機" },
    // その他IT・インフラ系
    MINNA_NO_TAXI:    { id: "minna-no-taxi",     label: "みんなのタクシー" },
    SOFTBANK:         { id: "softbank",          label: "ソフトバンク" },
    NEC:              { id: "nec",               label: "NEC" },
    NTT_DOCOMO:       { id: "ntt-docomo",        label: "NTTドコモ" },
    JTEKT:            { id: "jtekt",             label: "ジェイテクト" },
    KCCS:             { id: "kccs",              label: "KCCS" },
    UNKNOWN:          { id: "unknown-ads",       label: "不明" },
  };

  // ─────────────────────────────────────────────
  // KNOWN_ORGS: 既知の組織名正規表記リスト
  // stakeholders[].name のバリデーションに使用（警告レベル）
  // 複数組織が「、」区切りで記載される場合があるため、バリデータ側で分割後に照合する
  // 新規組織を追加した際はここにも追記する
  // ─────────────────────────────────────────────
  const KNOWN_ORGS = [
    // 企業・民間団体
    "A-Drive",
    "a2z（韓国）",
    "Auve Tech（エストニア）",
    "BOLDLY株式会社",
    "BRJ株式会社",
    "BYD（比亜迪）",
    "Cruise",
    "eve autonomy",
    "EVモーターズ・ジャパン株式会社",
    "Hyundai（現代自動車）",
    "JR四国",
    "JTB",
    "KDDI株式会社",
    "MONET Technologies株式会社",
    "Navya（フランス）",
    "NTTビジネスソリューションズ株式会社",
    "NTT西日本株式会社",
    "NVIDIA",
    "Uber Technologies",
    "Wayve",
    "WeRide（中国）",
    "WILLER株式会社",
    "アイサンテクノロジー株式会社",
    "アルピコ交通株式会社",
    "いすゞ自動車株式会社",
    "えちぜん鉄道株式会社",
    "シダックス株式会社",
    "スギノマシン",
    "スズキ株式会社",
    "ゼネラル・モーターズ（GM）",
    "ゼンリン株式会社",
    "ソーシャルナレッジバンク合同会社（SKB）",
    "SBドライブ株式会社（現BOLDLY株式会社）",
    "ソフトバンク株式会社",
    "トヨタ自動車株式会社",
    "ネクスト・モビリティ株式会社",
    "パナソニック株式会社",
    "マクニカ株式会社",
    "みちのりホールディングス",
    "みんなのタクシー株式会社（現Mobility Technologies）",
    "ヤマト運輸株式会社",
    "ヤマハ発動機株式会社",
    "植西運送株式会社",
    "伊予鉄バス株式会社",
    "伊予鉄道株式会社",
    "茨城交通株式会社",
    "羽田みらい開発株式会社",
    "遠州鉄道株式会社",
    "花鶴タクシー有限会社",
    "楽天モバイル株式会社",
    "株式会社ZMP",
    "株式会社セネック",
    "株式会社ティアフォー",
    "株式会社ディー・エヌ・エー（DeNA）",
    "株式会社マクニカ",
    "株式会社長大",
    "株式会社電脳交通",
    "関越交通株式会社",
    "岐阜バス株式会社",
    "宮城交通株式会社",
    "京セラ株式会社",
    "京王電鉄バス株式会社",
    "京阪バス株式会社",
    "京阪電気鉄道株式会社",
    "京浜急行バス株式会社",
    "京浜急行電鉄",
    "恵那市等",
    "兼松株式会社",
    "古賀タクシー株式会社",
    "国際興業バス",
    "三重交通株式会社",
    "三菱ふそうトラック・バス株式会社",
    "三菱商事株式会社",
    "自動運転トラック開発事業者",
    "小田急電鉄株式会社",
    "新潟交通佐渡株式会社",
    "神奈川中央交通株式会社",
    "神姫バス株式会社",
    "西日本旅客鉄道株式会社（JR西日本）",
    "先進モビリティ株式会社",
    "大阪市高速電気軌道株式会社",
    "大成建設株式会社",
    "第一交通産業株式会社",
    "中国バス株式会社",
    "中日本高速道路株式会社（NEXCO中日本）",
    "東日本旅客鉄道株式会社（JR東日本）",
    "東武バスウエスト株式会社",
    "東武バス日光株式会社",
    "奈良交通株式会社",
    "那覇バス株式会社",
    "日ノ丸自動車株式会社",
    "日産自動車株式会社",
    "日置電機株式会社",
    "日本カーバイド工業",
    "日本ペイント・インダストリアルコーティングス株式会社",
    "日本工営株式会社",
    "日本中央バス株式会社",
    "日本電気株式会社（NEC）",
    "日本郵便株式会社",
    "日野自動車株式会社",
    "富士急行株式会社",
    "片山津温泉旅館組合",
    "本田技研工業株式会社",
    "名鉄バス株式会社",
    "琉球バス交通株式会社",
    "関西電力株式会社",
    "大成ロテック株式会社",
    "独立行政法人都市再生機構（UR都市機構）",
    // 自治体（市区町村）
    "芦北町（熊本県）",
    "さいたま市（埼玉県）",
    "つくば市（茨城県）",
    "むつ市（青森県）",
    "伊予市（愛媛県）",
    "伊勢市（三重県）",
    "飯南町（島根県）",
    "宇都宮市（栃木県）",
    "小樽市（北海道）",
    "宇部市（山口県）",
    "永平寺町（福井県）",
    "塩尻市（長野県）",
    "横芝光町（千葉県）",
    "横須賀市（神奈川県）",
    "横浜市（神奈川県）",
    "加賀市（石川県）",
    "春日井市（愛知県）",
    "嬉野市（佐賀県）",
    "岐阜市（岐阜県）",
    "京田辺市（京都府）",
    "京都市（京都府）",
    "境町（茨城県）",
    "熊本市（熊本県）",
    "桑名市（三重県）",
    "恵那市（岐阜県）",
    "古賀市（福岡県）",
    "高知市（高知県）",
    "高畠町（山形県）",
    "狛江市（東京都）",
    "佐賀市（佐賀県）",
    "佐渡市（新潟県）",
    "佐伯市（大分県）",
    "坂井市（福井県）",
    "堺市（大阪府）",
    "更別村（北海道）",
    "三郷町（奈良県）",
    "三田市（兵庫県）",
    "三豊市（香川県）",
    "四條畷市（大阪府）",
    "四万十市（高知県）",
    "四日市市（三重県）",
    "周南市（山口県）",
    "渋川市（群馬県）",
    "小松市（石川県）",
    "松江市（島根県）",
    "松山市（愛媛県）",
    "松茂町（徳島県）",
    "上士幌町（北海道）",
    "上小阿仁村（秋田県）",
    "上田市（長野県）",
    "常陸太田市（茨城県）",
    "盛岡市（岩手県）",
    "西宮市（兵庫県）",
    "西都市（宮崎県）",
    "石狩市（北海道）",
    "仙台市（宮城県）",
    "千代田区（東京都）",
    "千葉市（千葉県）",
    "川崎市（神奈川県）",
    "前橋市（群馬県）",
    "多摩市（東京都）",
    "瑞穂町（東京都）",
    "港区（東京都）",
    "太地町（和歌山県）",
    "対馬市（長崎県）",
    "大館市（秋田県）",
    "大阪市（大阪府）",
    "大津市（滋賀県）",
    "大田区（東京都）",
    "北谷町（沖縄県）",
    "中津川市（岐阜県）",
    "那賀町（徳島県）",
    "長井市（山形県）",
    "鳥取市（鳥取県）",
    "津山市（岡山県）",
    "東近江市（滋賀県）",
    "東広島市（広島県）",
    "東川町（北海道）",
    "豊中市（大阪府）",
    "当別町（北海道）",
    "南さつま市（鹿児島県）",
    "南城市（沖縄県）",
    "南小国町（熊本県）",
    "日進市（愛知県）",
    "日立市（茨城県）",
    "柏市（千葉県）",
    "八丈町（東京都）",
    "磐梯町（福島県）",
    "磐田市（静岡県）",
    "みやま市（福岡県）",
    "美郷町（島根県）",
    "彦根市（滋賀県）",
    "浜松市（静岡県）",
    "富山市（富山県）",
    "富士吉田市（山梨県）",
    "富士市（静岡県）",
    "福岡市（福岡県）",
    "福山市（広島県）",
    "平塚市（神奈川県）",
    "豊見城市（沖縄県）",
    "北九州市（福岡県）",
    "明和町（三重県）",
    "明日香村（奈良県）",
    "鳴門市（徳島県）",
    "弥彦村（新潟県）",
    "陸前高田市（岩手県）",
    "流山市（千葉県）",
    "浪江町（福島県）",
    "和歌山市（和歌山県）",
    "和光市（埼玉県）",
    "木津川市（京都府）",
    "立山町（富山県）",
    "大町市（長野県）",
    "宗像市（福岡県）",
    // 省庁・大学・研究機関・都道府県・公共団体
    "20年先の小豆島をつくるプロジェクト",
    "NPO法人 上小阿仁村移送サービス協会",
    "愛知県",
    "一般財団法人 日本自動車研究所（JARI）",
    "一般財団法人塩尻市振興公社",
    "一般社団法人ばんだい振興公社",
    "株式会社建設技術研究所",
    "岐阜県",
    "宮崎県",
    "京都スマートシティ推進協議会",
    "京都市交通局",
    "香川大学",
    "九州大学",
    "群馬県",
    "群馬大学(CRANTS)",
    "慶應義塾大学",
    "経済産業省",
    "警察庁",
    "広島県",
    "広島大学",
    "高知県",
    "国土技術政策総合研究所",
    "国土交通省",
    "国土交通省 近畿運輸局",
    "国土交通省 近畿地方整備局",
    "国土交通省 九州運輸局",
    "国土交通省 北陸地方整備局",
    "国立研究開発法人 産業技術総合研究所（産総研）",
    "佐賀県",
    "佐賀市交通局",
    "三重県",
    "山口県",
    "山梨県",
    "滋賀県",
    "青森県",
    "千葉県",
    "総務省",
    "大阪府",
    "筑波大学",
    "東京大学",
    "東京都",
    "東京都交通局",
    "東北大学",
    "徳島県",
    "栃木県",
    "名古屋大学",
    "奈良県",
    "内閣府SIP自動運転推進委員会",
    "福井県",
    "北海道運輸局",
    "明治大学 自動運転社会総合研究所",
  ];

  // ─────────────────────────────────────────────
  // KNOWN_ROLES: ステークホルダー役割の既知リスト（バリデーション用、警告レベル）
  // 新規役割を追加した際はここにも追記する
  // ─────────────────────────────────────────────
  const KNOWN_ROLES = [
    "運行管理・事業主体",
    "運行管理",
    "運行・システム開発",
    "運行主体",
    "運行主体・システム",
    "運行受託",
    "車両提供",
    "車両製造",
    "車両提供・技術協力",
    "車両提供・技術開発",
    "車両提供・全体統括",
    "車両開発・自動運転システム",
    "車両技術協力",
    "自動運転システム",
    "自動運転システム開発",
    "自動運転システム開発・車両提供",
    "自動運転システム等",
    "自動運転AI技術",
    "自動運転技術提供",
    "自治体",
    "自治体・事業主体",
    "自治体・運行依頼",
    "協力自治体",
    "事業主体",
    "事業主体・バス事業者",
    "事業主体（CooL4幹事）",
    "事業連携",
    "事業参画",
    "実証主体",
    "実証事業主体",
    "実証支援",
    "実証実験支援",
    "実験支援",
    "研究支援",
    "技術協力",
    "通信システム検証",
    "システム開発・運行管理",
    "システム・地図",
    "協力機関",
    "協力企業",
    "出資・支援",
    "支援",
    "支援機関",
    "道路管理者・支援",
    "参画企業",
    "地域連携",
    "配車プラットフォーム",
    "サービス運営・車両提供",
    "実施主体等",
    "運行・システム",
    "システム",
    "企業",
    "産学官連携",
    "産官連携",
    "運行支援",
    "自動運転OS",
    "サービス提供",
    "導入・実証主体",
    "導入主体",
    "高精度地図提供",
    "バス事業者",
    "トンネル管理・施設提供",
  ];

  exports.STATUS = STATUS;
  exports.PREF = PREF;
  exports.VEH = VEH;
  exports.ADS = ADS;
  exports.KNOWN_ORGS = KNOWN_ORGS;
  exports.KNOWN_ROLES = KNOWN_ROLES;

})(typeof module !== "undefined" ? module.exports : window);
