// LiDARカタログ データ定義
//
// 設計ルール:
//   1. manufacturer / category / scanningMethod / wavelength は必ず schema.js の定数を参照する
//      → 文字列リテラルで enum 値を書かない（タイポが undefined になりバリデーションで検出される）
//   2. specs 内の各フィールドは { value, refs } 形式（value: null は情報なし）
//   3. references の各エントリは { id, url, title, date, source, type } を必須とする
//      date は "YYYY-MM" または "YYYY" 形式。type は SRC_TYPE.* を使用する。
//
// 新規エントリ追加手順:
//   a. schema.js に未登録のメーカー・カテゴリ・走査方式があれば先に追加する
//   b. 本ファイルに製品エントリを追加する
//   c. node validate-data.mjs を実行してエラーがないか確認する
//   d. node check-sources.mjs --product <id> で参考文献URLを確認する

// ブラウザ: schema.js が先にロードされ M/SCAN/CAT/WAVE/SRC_TYPE はグローバル変数として利用可能
// Node.js:  validate-data.mjs / check-sources.mjs が global.* に注入してから本ファイルをロードする

const LIDARS = [

  // ════════════════════════════════════════════
  // Hesai Technology
  // ════════════════════════════════════════════
  {
    id: "hesai-at128",
    manufacturer: M.HESAI,
    name: "AT128",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.HYBRID,
    wavelength: WAVE.NM905,
    discontinued: false,
    specs: {
      channels:   { value: 128,          unit: "ch",       refs: [1] },
      maxRange:   { value: 210,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: 260,          unit: "m",        refs: [1] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 25.4,         unit: "°",        refs: [1] },
      resH:       { value: "0.1°",       unit: null,       refs: [1] },
      resV:       { value: "0.2°",       unit: null,       refs: [1] },
      pointRate:  { value: 1536000,      unit: "pts/s",    refs: [1] },
      power:      { value: 13.5,         unit: "W",        refs: [1] },
      size:       { value: "137 × 112 × 48 mm", unit: null, refs: [1] },
      weight:     { value: 940,          unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: "IP6K9K",     unit: null,       refs: [1] },
      interface:  { value: "Gigabit Ethernet", unit: null, refs: [1] },
    },
    release: { value: "2022年後半量産開始（発表: 2021年8月）", refs: [1] },
    useCases: "車載 ADAS・前方監視。理想汽車など多数のOEMに採用。",
    references: [
      { id: 1, url: "https://www.hesaitech.com/product/at128/", title: "AT128 Product Page", date: "2026-03", source: "Hesai Technology", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "hesai-at512",
    manufacturer: M.HESAI,
    name: "AT512",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.HYBRID,
    wavelength: WAVE.NM905,
    discontinued: false,
    specs: {
      channels:   { value: 512,          unit: "ch",       refs: [1] },
      maxRange:   { value: 300,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: 400,          unit: "m",        refs: [1] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 25.4,         unit: "°",        refs: [1] },
      resH:       { value: "0.05°",      unit: null,       refs: [1] },
      resV:       { value: "0.05°",      unit: null,       refs: [1] },
      pointRate:  { value: 12300000,     unit: "pts/s",    refs: [1] },
      power:      { value: 25,           unit: "W",        note: "推定", refs: [1] },
      size:       { value: "137 × 112 × 48 mm", unit: null, refs: [1] },
      weight:     { value: 950,          unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: "IP6K9K",     unit: null,       refs: [1] },
      interface:  { value: "Gigabit Ethernet", unit: null, refs: [1] },
    },
    release: { value: "2024年1月発表（CES 2024）", refs: [1] },
    useCases: "L3/L4自動運転フラッグシップ。超高解像度512本スキャニング。",
    references: [
      { id: 1, url: "https://www.hesaitech.com/product/at512/", title: "AT512 Product Page", date: "2026-03", source: "Hesai Technology", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "hesai-etx",
    manufacturer: M.HESAI,
    name: "ETX",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.HYBRID,
    wavelength: WAVE.NM905,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 225,          unit: "m",        note: "windshield裏設置時 @ 10%", refs: [1] },
      peakRange:  { value: 300,          unit: "m",        refs: [1] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 25,           unit: "°",        refs: [1] },
      resH:       { value: "0.05°",      unit: null,       refs: [1] },
      resV:       { value: "0.05°",      unit: null,       refs: [1] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: 10,           unit: "W",        refs: [1] },
      size:       { value: "高さ 30 mm", unit: null,       refs: [1] },
      weight:     { value: 500,          unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: "Cabin-install", unit: null,    refs: [1] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2024年発表", refs: [1] },
    useCases: "フロントガラス内側専用。薄型・低消費電力。ET25の後継機的位置づけ。",
    references: [
      { id: 1, url: "https://www.hesaitech.com/product/etx/", title: "ETX Product Page", date: "2026-03", source: "Hesai Technology", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "hesai-ftx",
    manufacturer: M.HESAI,
    name: "FTX",
    category: CAT.AUTO_SHORT,
    scanningMethod: SCAN.FLASH,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 100,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 100,          unit: "°",        refs: [1] },
      fovV:       { value: 75,           unit: "°",        refs: [1] },
      resH:       { value: "160 pixels", unit: null,       refs: [1] },
      resV:       { value: "120 pixels", unit: null,       refs: [1] },
      pointRate:  { value: 192000,       unit: "pts/s",    refs: [1] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2024年発表", refs: [1] },
    useCases: "死角検知・近距離センシング。可動部なしの完全ソリッドステート。",
    references: [
      { id: 1, url: "https://www.hesaitech.com/product/ftx/", title: "FTX Product Page", date: "2026-03", source: "Hesai Technology", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "hesai-pandar128",
    manufacturer: M.HESAI,
    name: "Pandar128",
    category: CAT.RESEARCH,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.NM905,
    discontinued: false,
    specs: {
      channels:   { value: 128,          unit: "ch",       refs: [1] },
      maxRange:   { value: 200,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 40,           unit: "°",        note: "-25° ~ +15°", refs: [1] },
      resH:       { value: "0.1°",       unit: null,       refs: [1] },
      resV:       { value: "0.125°",     unit: null,       refs: [1] },
      pointRate:  { value: 3456000,      unit: "pts/s",    note: "Single Return", refs: [1] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "Gigabit Ethernet", unit: null, refs: [1] },
    },
    release: { value: "2020年9月", refs: [1] },
    useCases: "L4/L5自動運転開発・ロボタクシー・自動運転トラック",
    references: [
      { id: 1, url: "https://www.hesaitech.com/product/pandar128/", title: "Pandar128 Product Page", date: "2026-03", source: "Hesai Technology", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "hesai-pandarxt32",
    manufacturer: M.HESAI,
    name: "PandarXT-32",
    category: CAT.ROBOTICS,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.NM905,
    discontinued: false,
    specs: {
      channels:   { value: 32,           unit: "ch",       refs: [1] },
      maxRange:   { value: 80,           unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: 120,          unit: "m",        refs: [1] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 31,           unit: "°",        note: "+16° ~ -15°", refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: "±1 cm",      unit: null,       refs: [1] },
      minRange:   { value: 0.05,         unit: "m",        refs: [1] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "ロボット・産業用途。自社ASICによるコスト最適化。",
    references: [
      { id: 1, url: "https://www.hesaitech.com/product/pandarxt-32/", title: "PandarXT-32 Product Page", date: "2026-03", source: "Hesai Technology", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Ouster（Velodyne レガシー製品含む）
  // ════════════════════════════════════════════
  {
    id: "ouster-os0",
    manufacturer: M.OUSTER,
    name: "OS0",
    category: CAT.ROBOTICS,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: "32/64/128",  unit: "ch",       refs: [1] },
      maxRange:   { value: 100,          unit: "m",        note: "@ 10% reflectivity (REV7)", refs: [1] },
      peakRange:  { value: 150,          unit: "m",        refs: [1] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 90,           unit: "°",        refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: 5242880,      unit: "pts/s",    refs: [1] },
      power:      { value: 14,           unit: "W",        refs: [1] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: 445,          unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: 0.1,          unit: "m",        refs: [1] },
      protection: { value: "IP68, IP69K", unit: null,      refs: [1] },
      interface:  { value: "Gigabit Ethernet", unit: null, refs: [1] },
    },
    release: { value: "REV7: 2023年発表", refs: [1] },
    useCases: "AMR・屋内マッピング・超広角FOV用途（垂直90°）",
    references: [
      { id: 1, url: "https://ouster.com/products/hardware/os0-lidar-sensor/", title: "Ouster OS0 Product Page", date: "2026-03", source: "Ouster", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "ouster-os1",
    manufacturer: M.OUSTER,
    name: "OS1",
    category: CAT.ROBOTICS,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: "32/64/128",  unit: "ch",       refs: [1] },
      maxRange:   { value: 200,          unit: "m",        note: "@ 10% reflectivity (REV7)", refs: [1] },
      peakRange:  { value: 250,          unit: "m",        refs: [1] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 45,           unit: "°",        refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: 5242880,      unit: "pts/s",    note: "Max", refs: [1] },
      power:      { value: 14,           unit: "W",        refs: [1] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: 445,          unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: 0.1,          unit: "m",        refs: [1] },
      protection: { value: "IP68, IP69K", unit: null,      refs: [1] },
      interface:  { value: "Gigabit Ethernet", unit: null, refs: [1] },
    },
    release: { value: "REV7: 2023年発表", refs: [1] },
    useCases: "自動運転・ロボティクス・マッピング・多用途。REV7で検知距離が倍増。",
    references: [
      { id: 1, url: "https://ouster.com/products/hardware/os1-lidar-sensor/", title: "Ouster OS1 Product Page", date: "2026-03", source: "Ouster", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "ouster-os2",
    manufacturer: M.OUSTER,
    name: "OS2",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: "64/128",     unit: "ch",       refs: [1] },
      maxRange:   { value: 400,          unit: "m",        note: "@ 10% reflectivity (REV7)", refs: [1] },
      peakRange:  { value: 450,          unit: "m",        refs: [1] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 22.5,         unit: "°",        refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: 5242880,      unit: "pts/s",    refs: [1] },
      power:      { value: 20,           unit: "W",        refs: [1] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: 930,          unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: 0.5,          unit: "m",        refs: [1] },
      protection: { value: "IP68, IP69K", unit: null,      refs: [1] },
      interface:  { value: "Gigabit Ethernet", unit: null, refs: [1] },
    },
    release: { value: "REV7: 2023年発表", refs: [1] },
    useCases: "高速自動運転向け長距離センシング。REV7で400m検知を実現。",
    references: [
      { id: 1, url: "https://ouster.com/products/hardware/os2-lidar-sensor/", title: "Ouster OS2 Product Page", date: "2026-03", source: "Ouster", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "velodyne-vlp16",
    manufacturer: M.VELODYNE,
    name: "VLP-16 (Puck)",
    category: CAT.ROBOTICS,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.NM905,
    discontinued: true,
    specs: {
      channels:   { value: 16,           unit: "ch",       refs: [1] },
      maxRange:   { value: 100,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 30,           unit: "°",        note: "+15° ~ -15°", refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: "2.0°",       unit: null,       refs: [1] },
      pointRate:  { value: 300000,       unit: "pts/s",    note: "Single Return", refs: [1] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: "±3 cm",      unit: null,       refs: [1] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: "2014年発表・2016年頃から広く普及", refs: [1] },
    useCases: "研究開発・自動運転プロトタイピングのデファクトスタンダード",
    references: [
      { id: 1, url: "https://ouster.com/products/puck/", title: "Velodyne VLP-16 Product Page", date: "2026-03", source: "Ouster", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "velodyne-vls128",
    manufacturer: M.VELODYNE,
    name: "VLS-128 (Alpha Prime)",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.NM905,
    discontinued: true,
    specs: {
      channels:   { value: 128,          unit: "ch",       refs: [1] },
      maxRange:   { value: 245,          unit: "m",        note: "typical", refs: [1] },
      peakRange:  { value: 300,          unit: "m",        refs: [1] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 40,           unit: "°",        refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: "0.11°",      unit: null,       note: "Min", refs: [1] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "高速道路自動運転・L4開発用長距離高解像度",
    references: [
      { id: 1, url: "https://ouster.com/products/alpha-prime/", title: "Velodyne Alpha Prime Product Page", date: "2026-03", source: "Ouster", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Livox Technology
  // ════════════════════════════════════════════
  {
    id: "livox-mid360",
    manufacturer: M.LIVOX,
    name: "Mid-360",
    category: CAT.ROBOTICS,
    scanningMethod: SCAN.NON_REPETITIVE,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 40,           unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: 70,           unit: "m",        note: "@ 80%", refs: [1] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 59,           unit: "°",        note: "-7° ~ +52°", refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: 200000,       unit: "pts/s",    refs: [1] },
      power:      { value: 6.5,          unit: "W",        refs: [1] },
      size:       { value: "65 × 65 × 60 mm", unit: null,  refs: [1] },
      weight:     { value: 265,          unit: "g",        refs: [1] },
      accuracy:   { value: "±2 cm",      unit: null,       refs: [1] },
      minRange:   { value: 0.1,          unit: "m",        refs: [1] },
      protection: { value: "IP67",       unit: null,       refs: [1] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: "2023年1月", refs: [1] },
    useCases: "ロボット・産業用途。超コンパクト・軽量・高コストパフォーマンス。",
    references: [
      { id: 1, url: "https://www.livoxtech.com/mid-360", title: "Livox Mid-360 Product Page", date: "2026-03", source: "Livox Technology", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "livox-avia",
    manufacturer: M.LIVOX,
    name: "Avia",
    category: CAT.ROBOTICS,
    scanningMethod: SCAN.NON_REPETITIVE,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 190,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: 450,          unit: "m",        note: "@ 80%", refs: [1] },
      fovH:       { value: 70.4,         unit: "°",        note: "円形 FOV", refs: [1] },
      fovV:       { value: 77.2,         unit: "°",        note: "非反復走査時", refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: 720000,       unit: "pts/s",    note: "Max (Triple Return)", refs: [1] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: 498,          unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "ドローン搭載・測量・送電線点検",
    references: [
      { id: 1, url: "https://www.livoxtech.com/products/avia", title: "Livox Avia Product Page", date: "2026-03", source: "Livox Technology", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "livox-hap",
    manufacturer: M.LIVOX,
    name: "HAP",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.NON_REPETITIVE,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 150,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 25,           unit: "°",        refs: [1] },
      resH:       { value: "0.18°",      unit: null,       refs: [1] },
      resV:       { value: "0.23°",      unit: null,       refs: [1] },
      pointRate:  { value: 452000,       unit: "pts/s",    refs: [1] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: "105 × 132 × 65 mm", unit: null, refs: [1] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: "IP67",       unit: null,       refs: [1] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: "2021年量産開始（XPeng P5搭載）。2022年7月一般受注開始。", refs: [1, 2] },
    useCases: "車載グレード量産向け。XPeng P5などに採用。",
    references: [
      { id: 1, url: "https://www.livoxtech.com/products/hap", title: "Livox HAP Product Page", date: "2026-03", source: "Livox Technology", type: SRC_TYPE.PRODUCT_PAGE },
      { id: 2, url: "https://www.livoxtech.com/news/12", title: "Livox Press Release - Xpeng", date: "2026-03", source: "Livox Technology", type: SRC_TYPE.PRESS_RELEASE },
    ],
  },

  // ════════════════════════════════════════════
  // RoboSense
  // ════════════════════════════════════════════
  {
    id: "robosense-m1",
    manufacturer: M.ROBOSENSE,
    name: "RS-LiDAR-M1",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MEMS,
    wavelength: WAVE.NM905,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 200,          unit: "m",        note: "@ 10% reflectivity (M1 Plus)", refs: [1] },
      peakRange:  { value: 250,          unit: "m",        refs: [1] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 25,           unit: "°",        refs: [1] },
      resH:       { value: "0.2°",       unit: null,       note: "平均", refs: [1] },
      resV:       { value: "0.2°",       unit: null,       refs: [1] },
      pointRate:  { value: 1500000,      unit: "pts/s",    note: "Dual Return", refs: [1] },
      power:      { value: 15,           unit: "W",        refs: [1] },
      size:       { value: "108 × 110 × 45 mm", unit: null, refs: [1] },
      weight:     { value: 800,          unit: "g",        refs: [1] },
      accuracy:   { value: "±3 cm",      unit: null,       refs: [1] },
      minRange:   { value: 0.5,          unit: "m",        refs: [1] },
      protection: { value: "IP6K9K",     unit: null,       refs: [1] },
      interface:  { value: "1 Gbps Ethernet", unit: null,  refs: [1] },
    },
    release: { value: "2021年6月量産開始", refs: [1] },
    useCases: "世界初の量産車載グレードMEMS LiDAR。M1 Plusにアップグレード済み。",
    references: [
      { id: 1, url: "https://www.robosense.ai/en/products/m-series/m1", title: "RoboSense M1 Product Page", date: "2026-03", source: "RoboSense", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "robosense-m3",
    manufacturer: M.ROBOSENSE,
    name: "RS-LiDAR-M3",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MEMS,
    wavelength: WAVE.NM940,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 300,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 25,           unit: "°",        refs: [1] },
      resH:       { value: "0.05°",      unit: null,       note: "ROI等価500ビーム", refs: [1] },
      resV:       { value: "0.05°",      unit: null,       refs: [1] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: "IP6K9K",     unit: null,       refs: [1] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2024年発表（CES 2024）", refs: [1] },
    useCases: "L3+自動運転・高速120km/h対応フラッグシップ機",
    references: [
      { id: 1, url: "https://www.robosense.ai/en/products/m-series/m3", title: "RoboSense M3 Product Page", date: "2026-03", source: "RoboSense", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "robosense-mx",
    manufacturer: M.ROBOSENSE,
    name: "RS-LiDAR-MX",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MEMS,
    wavelength: WAVE.NM905,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 200,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 25,           unit: "°",        refs: [1] },
      resH:       { value: "0.1°",       unit: null,       refs: [1] },
      resV:       { value: "0.1°",       unit: null,       refs: [1] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: 10,           unit: "W",        refs: [1] },
      size:       { value: "高さ 25 mm", unit: null,       refs: [1] },
      weight:     { value: 600,          unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: "IP6K9K",     unit: null,       refs: [1] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2024年発表", refs: [1] },
    useCases: "超薄型・低消費電力モデル。フロントガラス内側等への設置に最適。",
    references: [
      { id: 1, url: "https://www.robosense.ai/en/products/m-series/mx", title: "RoboSense MX Product Page", date: "2026-03", source: "RoboSense", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "robosense-bpearl",
    manufacturer: M.ROBOSENSE,
    name: "RS-Bpearl",
    category: CAT.AUTO_SHORT,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: 32,           unit: "ch",       refs: [1] },
      maxRange:   { value: 30,           unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: 100,          unit: "m",        refs: [1] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 90,           unit: "°",        refs: [1] },
      resH:       { value: "0.1° ~ 0.2°", unit: null,      refs: [1] },
      resV:       { value: "2.8°",       unit: null,       refs: [1] },
      pointRate:  { value: 576000,       unit: "pts/s",    note: "Single Return", refs: [1] },
      power:      { value: 28,           unit: "W",        refs: [1] },
      size:       { value: "Φ100 × 111 mm", unit: null,    refs: [1] },
      weight:     { value: 920,          unit: "g",        refs: [1] },
      accuracy:   { value: "±3 cm",      unit: null,       refs: [1] },
      minRange:   { value: 0.1,          unit: "m",        refs: [1] },
      protection: { value: "IP67",       unit: null,       refs: [1] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "低速物流ロボット・近接死角検知（垂直90°超広角）",
    references: [
      { id: 1, url: "https://www.robosense.ai/en/products/mechanical/bpearl", title: "RoboSense RS-Bpearl Product Page", date: "2026-03", source: "RoboSense", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "robosense-helios16p",
    manufacturer: M.ROBOSENSE,
    name: "RS-Helios-16P",
    category: CAT.ROBOTICS,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: 32,           unit: "ch",       refs: [1] },
      maxRange:   { value: 150,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: 31,           unit: "°",        note: "-16° ~ +15°", refs: [1] },
      resH:       { value: "0.2° / 0.4°", unit: null,      refs: [1] },
      resV:       { value: "1.0°",       unit: null,       refs: [1] },
      pointRate:  { value: 576000,       unit: "pts/s",    note: "Single Return", refs: [1] },
      power:      { value: 12,           unit: "W",        refs: [1] },
      size:       { value: "Φ100 × 100 mm", unit: null,    refs: [1] },
      weight:     { value: 1000,         unit: "g",        refs: [1] },
      accuracy:   { value: "±2 cm",      unit: null,       refs: [1] },
      minRange:   { value: 0.2,          unit: "m",        refs: [1] },
      protection: { value: "IP67",       unit: null,       refs: [1] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: "2021年10月", refs: [1] },
    useCases: "AGV/AMR・車載補助センサ。多チャンネル・高密度モデル。",
    references: [
      { id: 1, url: "https://www.robosense.ai/en/products/mechanical/helios", title: "RoboSense Helios Series Product Page", date: "2026-03", source: "RoboSense", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Aeva
  // ════════════════════════════════════════════
  {
    id: "aeva-aeries2",
    manufacturer: M.AEVA,
    name: "Aeries II",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.FMCW,
    wavelength: WAVE.NM1550,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 500,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: null, refs: [] },
    useCases: "車載ADAS。4D LiDARで速度直接計測。太陽光・他LiDAR干渉耐性。",
    references: [
      { id: 1, url: "https://www.aeva.com/aeries/", title: "Aeva Aeries II Product Page", date: "2026-03", source: "Aeva", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Luminar Technologies
  // ════════════════════════════════════════════
  {
    id: "luminar-iris",
    manufacturer: M.LUMINAR,
    name: "Iris",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.NM1550,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 600,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 28,           unit: "°",        refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    note: "最大300 pts/deg²", refs: [1] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2022年量産開始（Volvo EX90: 2024年6月生産開始）", refs: [1, 2] },
    useCases: "車載長距離前方監視。Volvo EX90・Mercedes・Polestar等に採用。",
    references: [
      { id: 1, url: "https://www.luminartech.com/technology/iris/", title: "Luminar Iris Product Page", date: "2026-03", source: "Luminar Technologies", type: SRC_TYPE.PRODUCT_PAGE },
      { id: 2, url: "https://www.volvocars.com/intl/v/cars/ex90", title: "Volvo EX90 - Luminar LiDAR搭載", date: "2026-03", source: "Volvo Cars", type: SRC_TYPE.NEWS },
    ],
  },
  {
    id: "luminar-halo",
    manufacturer: M.LUMINAR,
    name: "Halo",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.NM1550,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 300,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: 10,           unit: "W",        note: "Iris比約半分", refs: [1] },
      size:       { value: "Irisの約1/3の高さ", unit: null, refs: [1] },
      weight:     { value: 1000,         unit: "g",        refs: [1] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2024年4月発表", refs: [1] },
    useCases: "次世代超小型・低消費電力モデル。大幅な小型化を実現。",
    references: [
      { id: 1, url: "https://www.luminartech.com/technology/halo/", title: "Luminar Halo Product Page", date: "2026-03", source: "Luminar Technologies", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Innoviz Technologies
  // ════════════════════════════════════════════
  {
    id: "innoviz-one",
    manufacturer: M.INNOVIZ,
    name: "InnovizOne",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MEMS,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 250,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 115,          unit: "°",        refs: [1] },
      fovV:       { value: 25,           unit: "°",        refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: 17,           unit: "W",        refs: [1] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2021〜2022年（BMW iX搭載）", refs: [1] },
    useCases: "BMW iX・BMW 7シリーズ搭載",
    references: [
      { id: 1, url: "https://innoviz.tech/innovizone", title: "InnovizOne Product Page", date: "2026-03", source: "Innoviz Technologies", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "innoviz-two",
    manufacturer: M.INNOVIZ,
    name: "InnovizTwo",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MEMS,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 300,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 43,           unit: "°",        refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2023年以降（VW/CARIAD ID. Buzz: 2025〜）", refs: [1, 2] },
    useCases: "L2+〜L5対応。初代比「性能30倍・コスト70%削減」。VW CARIAD $40億規模契約。",
    references: [
      { id: 1, url: "https://innoviz.tech/innoviztwo", title: "InnovizTwo Product Page", date: "2026-03", source: "Innoviz Technologies", type: SRC_TYPE.PRODUCT_PAGE },
      { id: 2, url: "https://innoviz.tech/news", title: "Innoviz - VW/CARIAD Contract", date: "2026-03", source: "Innoviz Technologies", type: SRC_TYPE.PRESS_RELEASE },
    ],
  },

  // ════════════════════════════════════════════
  // Seyond（旧Innovusion）
  // ════════════════════════════════════════════
  {
    id: "seyond-falcon",
    manufacturer: M.SEYOND,
    name: "Falcon",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.NM1550,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 250,          unit: "m",        note: "@ 10% reflectivity", refs: [1] },
      peakRange:  { value: 500,          unit: "m",        refs: [1] },
      fovH:       { value: 120,          unit: "°",        refs: [1] },
      fovV:       { value: 25,           unit: "°",        refs: [1] },
      resH:       { value: "0.18°",      unit: null,       note: "ROI外; ROI内 0.09°", refs: [1] },
      resV:       { value: "0.24°",      unit: null,       note: "ROI外; ROI内 0.08°", refs: [1] },
      pointRate:  { value: null,         unit: "pts/s",    note: "約1,500走査線/秒", refs: [1] },
      power:      { value: 30,           unit: "W",        refs: [1] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2022年Q1（NIO ET7量産開始に合わせて）", refs: [1] },
    useCases: "NIO ET7・ES7・ET5（NT2.0プラットフォーム）に標準搭載",
    references: [
      { id: 1, url: "https://www.seyond.com/falcon/", title: "Seyond Falcon Product Page", date: "2026-03", source: "Seyond", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Valeo
  // ════════════════════════════════════════════
  {
    id: "valeo-scala1",
    manufacturer: M.VALEO,
    name: "SCALA 1",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: true,
    specs: {
      channels:   { value: 4,            unit: "ch",       refs: [1] },
      maxRange:   { value: 150,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2017年（Audi A8搭載）", refs: [1] },
    useCases: "世界初の量産車搭載LiDAR。Audi A8 渋滞自動運転（L3）実現。",
    references: [
      { id: 1, url: "https://www.valeo.com/en/our-products/lidar/", title: "Valeo SCALA LiDAR Products", date: "2026-03", source: "Valeo", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "valeo-scala2",
    manufacturer: M.VALEO,
    name: "SCALA 2",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 200,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2021年", refs: [1] },
    useCases: "Mercedes-Benz DRIVE PILOT（L3）に採用。Honda Legend L3にも採用。",
    references: [
      { id: 1, url: "https://www.valeo.com/en/our-products/lidar/", title: "Valeo SCALA LiDAR Products", date: "2026-03", source: "Valeo", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "valeo-scala3",
    manufacturer: M.VALEO,
    name: "SCALA 3",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: null,         unit: "m",        refs: [] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: 4500000,      unit: "pts/s",    note: "SCALA 2比「約50倍の点群密度」", refs: [1] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2024年以降", refs: [1] },
    useCases: "130km/h高速道路自動運転対応。SCALA 2比50倍の点群密度。",
    references: [
      { id: 1, url: "https://www.valeo.com/en/our-products/lidar/", title: "Valeo SCALA LiDAR Products", date: "2026-03", source: "Valeo", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Denso
  // ════════════════════════════════════════════
  {
    id: "denso-spad",
    manufacturer: M.DENSO,
    name: "SPADソリッドステートLiDAR",
    category: CAT.RESEARCH,
    scanningMethod: SCAN.FLASH,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 200,          unit: "m",        note: "目標値", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2025年頃市場投入目標", refs: [1] },
    useCases: "次世代高性能車載LiDAR。AMD(Xilinx) FPGA搭載で高精度処理。",
    references: [
      { id: 1, url: "https://www.denso.com/global/en/innovation/technology/lidar/", title: "Denso LiDAR Technology", date: "2026-03", source: "Denso", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "denso-fmcw",
    manufacturer: M.DENSO,
    name: "FMCWソリッドステートLiDAR（Aevaと共同開発）",
    category: CAT.RESEARCH,
    scanningMethod: SCAN.FMCW,
    wavelength: WAVE.NM1550,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: null,         unit: "m",        refs: [] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: null, refs: [] },
    useCases: "4D LiDAR（速度直接計測）。太陽光・干渉耐性。Aevaとの共同開発品。",
    references: [
      { id: 1, url: "https://www.denso.com/global/en/innovation/technology/lidar/", title: "Denso LiDAR Technology", date: "2026-03", source: "Denso", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Pioneer Smart Sensing Innovations（PSSP）
  // ════════════════════════════════════════════
  {
    id: "pioneer-3d-gen1",
    manufacturer: M.PIONEER,
    name: "3D-LiDAR Gen1",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MEMS,
    wavelength: WAVE.NM905,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: null,         unit: "m",        note: "先代比1.5〜2倍改善", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: "775 cc",     unit: null,       refs: [1] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2020年以降", refs: [1] },
    useCases: "L3+自動運転・モビリティサービス・ロボティクス",
    references: [
      { id: 1, url: "https://www.pioneer-pssp.co.jp/", title: "Pioneer PSSP 公式サイト", date: "2026-03", source: "Pioneer PSSP", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Hokuyo Automatic
  // ════════════════════════════════════════════
  {
    id: "hokuyo-ust10lx",
    manufacturer: M.HOKUYO,
    name: "UST-10LX",
    category: CAT.INDUSTRIAL,
    scanningMethod: SCAN.MECHANICAL_2D,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 10,           unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 270,          unit: "°",        refs: [1] },
      fovV:       { value: null,         unit: "°",        note: "2D スキャナ", refs: [] },
      resH:       { value: "0.25°",      unit: null,       refs: [1] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: 0.06,         unit: "m",        refs: [1] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "AGV・AMR・屋内ロボット用2D測域センサ。ROSドライバ充実。",
    references: [
      { id: 1, url: "https://www.hokuyo-aut.co.jp/search/single.php?serial=21", title: "Hokuyo UST-10LX Product Page", date: "2026-03", source: "Hokuyo Automatic", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "hokuyo-ust30lx",
    manufacturer: M.HOKUYO,
    name: "UST-30LX",
    category: CAT.INDUSTRIAL,
    scanningMethod: SCAN.MECHANICAL_2D,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 30,           unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 270,          unit: "°",        refs: [1] },
      fovV:       { value: null,         unit: "°",        note: "2D スキャナ", refs: [] },
      resH:       { value: "0.25°",      unit: null,       refs: [1] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: 0.06,         unit: "m",        refs: [1] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "Ethernet",   unit: null,       refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "AGV・AMR・屋外ロボット用2D測域センサ。30m長距離対応。",
    references: [
      { id: 1, url: "https://www.hokuyo-aut.co.jp/search/single.php?serial=22", title: "Hokuyo UST-30LX Product Page", date: "2026-03", source: "Hokuyo Automatic", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "hokuyo-yvt35lx",
    manufacturer: M.HOKUYO,
    name: "YVT-35LX",
    category: CAT.INDUSTRIAL,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: null,         unit: "m",        refs: [] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 210,          unit: "°",        refs: [1] },
      fovV:       { value: 40,           unit: "°",        refs: [1] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: null, refs: [] },
    useCases: "3D産業用LiDAR。低反射率物体の検知強化。",
    references: [
      { id: 1, url: "https://www.hokuyo-aut.co.jp/", title: "Hokuyo Automatic 公式サイト", date: "2026-03", source: "Hokuyo Automatic", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // SICK AG
  // ════════════════════════════════════════════
  {
    id: "sick-tim781",
    manufacturer: M.SICK,
    name: "TiM781",
    category: CAT.INDUSTRIAL,
    scanningMethod: SCAN.MECHANICAL_2D,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 25,           unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 270,          unit: "°",        refs: [1] },
      fovV:       { value: null,         unit: "°",        note: "2D スキャナ", refs: [] },
      resH:       { value: "0.33°",      unit: null,       refs: [1] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: 0.05,         unit: "m",        refs: [1] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "USB / Ethernet", unit: null,   refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "屋内外AGV・AMR・モバイルロボット用コンパクト2Dスキャナ",
    references: [
      { id: 1, url: "https://www.sick.com/de/en/catalog/products/lidar-and-radar-sensors/lidar-sensors/tim7xx/c/g575498", title: "SICK TiM Series Product Page", date: "2026-03", source: "SICK AG", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "sick-microscan3",
    manufacturer: M.SICK,
    name: "microScan3",
    category: CAT.INDUSTRIAL,
    scanningMethod: SCAN.MECHANICAL_2D,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 9,            unit: "m",        note: "安全保護範囲", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 275,          unit: "°",        refs: [1] },
      fovV:       { value: null,         unit: "°",        note: "2D スキャナ", refs: [] },
      resH:       { value: "0.1°",       unit: null,       refs: [1] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: "IP65",       unit: null,       refs: [1] },
      interface:  { value: "EtherNet/IP, PROFINET", unit: null, refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "機能安全認証（SIL2/PLd）安全スキャナ。衝突防止・保護ゾーン管理。",
    references: [
      { id: 1, url: "https://www.sick.com/microscan3", title: "SICK microScan3 Product Page", date: "2026-03", source: "SICK AG", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Koito Manufacturing
  // ════════════════════════════════════════════
  {
    id: "koito-headlamp-lidar",
    manufacturer: M.KOITO,
    name: "ヘッドランプ統合型LiDAR（Cepton MMT）",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.MEMS,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: null,         unit: "m",        refs: [] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "Cepton買収完了: 2025年1月", refs: [1] },
    useCases: "ヘッドランプハウジングにLiDARを統合。デザイン制約なし・4隅配置で360度対応。",
    references: [
      { id: 1, url: "https://www.koito.co.jp/", title: "Koito Manufacturing 公式サイト", date: "2026-03", source: "Koito Manufacturing", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Kyocera
  // ════════════════════════════════════════════
  {
    id: "kyocera-camera-lidar",
    manufacturer: M.KYOCERA,
    name: "カメラ・LiDAR融合センサ",
    category: CAT.AUTO_LONG,
    scanningMethod: SCAN.CAMERA_LIDAR,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 100,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: "0.045°",     unit: null,       refs: [1] },
      resV:       { value: "0.045°",     unit: null,       refs: [1] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2025年3月商用化目標", refs: [1] },
    useCases: "カメラとLiDARの光軸を一致させ視差なしのデータ統合。セラミックMEMSミラー採用。",
    references: [
      { id: 1, url: "https://www.kyocera.co.jp/", title: "Kyocera 公式サイト（センサ事業）", date: "2026-03", source: "Kyocera", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // LeddarTech
  // ════════════════════════════════════════════
  {
    id: "leddartech-leddarvision",
    manufacturer: M.LEDDARTECH,
    name: "LeddarVision",
    category: CAT.SOFTWARE,
    scanningMethod: SCAN.SOFTWARE,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: null,         unit: "m",        refs: [] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: null, refs: [] },
    useCases: "カメラ・レーダー・LiDARのローレベル融合知覚ソフト。L2〜L4対応。Ficosa・Visteonと協業。",
    references: [
      { id: 1, url: "https://leddartech.com/leddarvision/", title: "LeddarTech LeddarVision", date: "2026-03", source: "LeddarTech", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Quanergy Solutions
  // ════════════════════════════════════════════
  {
    id: "quanergy-m8",
    manufacturer: M.QUANERGY,
    name: "M8",
    category: CAT.INDUSTRIAL,
    scanningMethod: SCAN.MECHANICAL,
    wavelength: WAVE.UNKNOWN,
    discontinued: true,
    specs: {
      channels:   { value: 8,            unit: "ch",       refs: [1] },
      maxRange:   { value: 200,          unit: "m",        refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: 360,          unit: "°",        refs: [1] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        note: "PoE駆動", refs: [1] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: "PoE Ethernet", unit: null,     refs: [1] },
    },
    release: { value: null, refs: [] },
    useCases: "物理セキュリティ・スマートスペース・産業IoT（2022年破産申請後、セキュリティ特化で再建中）",
    references: [
      { id: 1, url: "https://quanergy.com/products/m8/", title: "Quanergy M8 Product Page", date: "2026-03", source: "Quanergy Solutions", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },
  {
    id: "quanergy-s3",
    manufacturer: M.QUANERGY,
    name: "S3",
    category: CAT.INDUSTRIAL,
    scanningMethod: SCAN.OPA,
    wavelength: WAVE.UNKNOWN,
    discontinued: true,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: null,         unit: "m",        refs: [] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: null,         unit: null,       refs: [] },
      resV:       { value: null,         unit: null,       refs: [] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: null, refs: [] },
    useCases: "OPA方式で完全可動部なし。MTBF 100,000時間以上。走査パターンをソフトウェア設定。",
    references: [
      { id: 1, url: "https://quanergy.com/products/s3/", title: "Quanergy S3 Product Page", date: "2026-03", source: "Quanergy Solutions", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

  // ════════════════════════════════════════════
  // Toshiba
  // ════════════════════════════════════════════
  {
    id: "toshiba-sipm",
    manufacturer: M.TOSHIBA,
    name: "SiPM LiDAR",
    category: CAT.RESEARCH,
    scanningMethod: SCAN.SIPM,
    wavelength: WAVE.UNKNOWN,
    discontinued: false,
    specs: {
      channels:   { value: null,         unit: "ch",       refs: [] },
      maxRange:   { value: 300,          unit: "m",        note: "改良モデル", refs: [1] },
      peakRange:  { value: null,         unit: "m",        refs: [] },
      fovH:       { value: null,         unit: "°",        refs: [] },
      fovV:       { value: null,         unit: "°",        refs: [] },
      resH:       { value: "1200 pixels", unit: null,      refs: [1] },
      resV:       { value: "80 pixels",  unit: null,       refs: [1] },
      pointRate:  { value: null,         unit: "pts/s",    refs: [] },
      power:      { value: null,         unit: "W",        refs: [] },
      size:       { value: null,         unit: null,       refs: [] },
      weight:     { value: null,         unit: null,       refs: [] },
      accuracy:   { value: null,         unit: null,       refs: [] },
      minRange:   { value: null,         unit: "m",        refs: [] },
      protection: { value: null,         unit: null,       refs: [] },
      interface:  { value: null,         unit: null,       refs: [] },
    },
    release: { value: "2025年度商用化目標（2026年3月期）", refs: [1] },
    useCases: "自動車・インフラ監視・定点セキュリティ。SAT技術で太陽光ノイズ耐性。",
    references: [
      { id: 1, url: "https://www.global.toshiba/ww/products-solutions/ai-iot/lidar.html", title: "Toshiba LiDAR Technology", date: "2026-03", source: "Toshiba Corporation", type: SRC_TYPE.PRODUCT_PAGE },
    ],
  },

];

// ブラウザ・Node.js 両対応のエクスポート
if (typeof module !== "undefined") {
  module.exports = { LIDARS };
} else {
  window.LIDARS = LIDARS;
}
